export const LEVEL_GUIDE = {
  levels: [
    {
      id: "user",
      name: "User Level",
      range: "LV 1 - 300",
      icon: "👤",
      gradient: "from-blue-500 to-indigo-600",
      color: "#3B82F6",
      whatIs: "User Level represents your overall activity and engagement across the VYRO platform. The more active you are, the faster your User Level will increase.",
      howToIncrease: [
        "Sending Gifts",
        "Receiving Gifts",
        "Joining Party Rooms",
        "Voice Chat Activity",
        "Daily Login Rewards",
        "Completing Daily Tasks",
        "Participating in Events",
        "Following Other Users",
        "Room Engagement",
        "Platform Activity",
      ],
      benefits: [
        "Premium Profile Frames",
        "Animated Badges",
        "Exclusive Chat Bubbles",
        "Username Colors",
        "Entrance Effects",
        "VIP Recognition",
        "Exclusive Events Access",
        "Higher Profile Visibility",
        "Special Achievement Rewards",
      ],
      iconSystem: [
        "Bronze Crystal",
        "Silver Crystal",
        "Gold Crystal",
        "Platinum Crystal",
        "Diamond Crystal",
        "Sapphire Crown",
        "Ruby Crown",
        "Galaxy Crown",
      ],
      rule: "User Level increases through overall platform activity, engagement, participation, and gifting behavior.",
    },
    {
      id: "host",
      name: "Host Level",
      range: "LV 1 - 300",
      icon: "🎙️",
      gradient: "from-red-400 to-orange-500",
      color: "#EF4444",
      whatIs: "Host Level measures your performance and success as a host on VYRO Live Connect.",
      howToIncrease: [
        "Gifts Received During Streams",
        "Hosting Live Streams",
        "Party Room Hosting",
        "Viewer Engagement",
        "Audience Retention",
        "PK Battles Participation",
        "Event Rankings",
        "Daily Host Missions",
        "Stream Performance",
      ],
      benefits: [
        "Featured Host Placement",
        "Homepage Promotion",
        "Verified Host Badge",
        "Premium Broadcast Effects",
        "Exclusive Host Frames",
        "Higher Discovery Ranking",
        "Priority Event Access",
        "Advanced Analytics",
        "Priority Support",
      ],
      iconSystem: [
        "Bronze Microphone",
        "Silver Microphone",
        "Gold Microphone",
        "Platinum Stage",
        "Diamond Stage",
        "Royal Stage",
        "Galaxy Stage",
      ],
      rule: "Host Level increases through hosting performance, audience growth, stream quality, and gifts received.",
    },
    {
      id: "gifting",
      name: "Gifting Level",
      range: "LV 1 - 200",
      icon: "🎁",
      gradient: "from-amber-400 to-yellow-500",
      color: "#F59E0B",
      whatIs: "Gifting Level represents your support for creators, hosts, and the VYRO community through gifting.",
      howToIncrease: [
        "Sending Gifts in Live Streams",
        "Sending Gifts in Party Rooms",
        "Sending Event Gifts",
        "Sending Premium Gifts",
        "Participating in PK Battle Gifting",
      ],
      benefits: [
        "Luxury Profile Frames",
        "Animated Sender Badge",
        "Premium Gift Effects",
        "Exclusive Gifts Access",
        "Gift Broadcast Priority",
        "VIP Name Glow",
        "Luxury Entrance Effects",
        "Elite Gifter Recognition",
      ],
      iconSystem: [
        "Bronze Gift Box",
        "Silver Gift Box",
        "Gold Gift Box",
        "Diamond Gift Box",
        "Royal Treasure Chest",
        "Mythic Treasure",
      ],
      rule: "Gifting Level increases only through sending gifts and supporting other users.",
    },
    {
      id: "streaming",
      name: "Streaming Level",
      range: "LV 1 - 200",
      icon: "📡",
      gradient: "from-blue-400 to-cyan-500",
      color: "#06B6D4",
      whatIs: "Streaming Level measures the popularity and performance of your stream, room, or live session.",
      howToIncrease: [
        "Gifts Received",
        "Viewer Count",
        "Watch Time",
        "Likes Received",
        "Shares Received",
        "Audience Engagement",
        "Room Popularity",
        "Event Participation",
        "Stream Activity",
      ],
      benefits: [
        "Discovery Boost",
        "Trending Placement",
        "Featured Stream Placement",
        "Premium Stream Decorations",
        "Exclusive Room Themes",
        "Event Priority Access",
        "Enhanced Visibility",
        "Stream Achievement Rewards",
      ],
      iconSystem: [
        "Bronze Broadcast Tower",
        "Silver Broadcast Tower",
        "Gold Broadcast Tower",
        "Diamond Broadcast Tower",
        "Galaxy Broadcast Tower",
      ],
      rule: "Streaming Level increases through stream popularity, audience engagement, and gifts received during streams.",
    },
  ],
  example: {
    multiLevel: [
      { label: "User Level", value: 120, color: "#3B82F6" },
      { label: "Host Level", value: 85, color: "#EF4444" },
      { label: "Gifting Level", value: 60, color: "#F59E0B" },
      { label: "Streaming Level", value: 45, color: "#06B6D4" },
    ],
    scenarioGifting: [
      "Sends gifts worth 1,000,000 coins",
      "Completes daily missions",
      "Joins party rooms",
      "Participates in events",
    ],
    scenarioHosting: [
      "Receives gifts",
      "Gains viewers",
      "Maintains audience engagement",
    ],
  },
  ultimateRewards: [
    {
      tier: "Level 100+",
      icon: "🥈",
      color: "#94A3B8",
      rewards: [
        "Animated Profile Frame",
        "Premium Chat Bubble",
        "Entrance Effect",
      ],
    },
    {
      tier: "Level 200+",
      icon: "🥇",
      color: "#EAB308",
      rewards: [
        "3D Animated Badge",
        "Aura Effect",
        "Exclusive Theme",
      ],
    },
    {
      tier: "Level 250+",
      icon: "👑",
      color: "#A855F7",
      rewards: [
        "Golden Wings Entrance",
        "Premium Username Glow",
        "VIP Support Priority",
      ],
    },
    {
      tier: "Level 300",
      icon: "💎",
      color: "#6366F1",
      rewards: [
        "Mythic 3D Animated Crown",
        "Cosmic Aura Effect",
        "Global Broadcast Banner",
        "Legendary Entrance Animation",
        "Exclusive Profile Theme",
        "Limited Edition Gifts",
        "Elite Platform Recognition",
      ],
    },
  ],
};