export const levelSystems = [
  {
    id: "user",
    name: "User Level",
    icon: "👤",
    level: 35,
    progress: 80,
    remainingXp: 17600,
    nextLevel: 36,
    color: "#A855F7",
    gradient: "from-purple-400 to-violet-600",
    iconSystem: [
      { name: "Bronze Crystal", icon: "🥉" },
      { name: "Silver Crystal", icon: "🥈" },
      { name: "Gold Crystal", icon: "🥇" },
      { name: "Platinum Crystal", icon: "💎" },
      { name: "Diamond Crystal", icon: "🔷" },
      { name: "Sapphire Crown", icon: "👑" },
      { name: "Ruby Crown", icon: "🔴" },
      { name: "Galaxy Crown", icon: "🌌" },
    ],
    about: "User Level represents your overall activity and engagement across VYRO Live Connect.",
    howToIncrease: ["Send Gifts", "Receive Gifts", "Join Party Rooms", "Complete Daily Tasks", "Daily Login Rewards", "Chat Activity", "Participate In Events"],
    levelRange: "31-40",
    coinsRequired: "15,000,000 Coins",
    description: "Stay active, send gifts, participate in events, and engage with the community to level up faster.",
  },
  {
    id: "host",
    name: "Host Level",
    icon: "🎙️",
    level: 18,
    progress: 62,
    remainingXp: 18800,
    nextLevel: 19,
    color: "#EF4444",
    gradient: "from-red-400 to-orange-500",
    iconSystem: [
      { name: "Bronze Microphone", icon: "🎤" },
      { name: "Silver Microphone", icon: "🎙️" },
      { name: "Gold Microphone", icon: "🥇" },
      { name: "Platinum Stage", icon: "🎭" },
      { name: "Diamond Stage", icon: "💎" },
      { name: "Royal Stage", icon: "👑" },
      { name: "Galaxy Stage", icon: "🌌" },
    ],
    about: "Host Level measures your success and performance as a host.",
    howToIncrease: ["Receive Gifts", "Stream Daily", "Increase Watch Time", "Gain More Active Viewers", "Participate In PK Battles", "Join Official Events"],
    levelRange: "11-20",
    coinsRequired: "5,000,000 Coins",
    description: "Receive more gifts and grow your audience to increase your Host Level faster.",
  },
  {
    id: "gift",
    name: "Gift Level",
    icon: "🎁",
    level: 40,
    progress: 88,
    remainingXp: 11900,
    nextLevel: 41,
    color: "#F59E0B",
    gradient: "from-amber-400 to-yellow-500",
    iconSystem: [
      { name: "Bronze Gift Box", icon: "📦" },
      { name: "Silver Gift Box", icon: "🎁" },
      { name: "Gold Gift Box", icon: "🥇" },
      { name: "Diamond Gift Box", icon: "💎" },
      { name: "Royal Treasure Chest", icon: "👑" },
      { name: "Mythic Treasure", icon: "✨" },
    ],
    about: "Gift Level reflects your gifting activity and support for hosts and creators.",
    howToIncrease: ["Send Gifts", "Send Event Gifts", "Send Party Room Gifts", "Send Premium Gifts"],
    levelRange: "31-40",
    coinsRequired: "75,000,000 Coins",
    description: "Send more gifts to unlock exclusive gifting rewards and increase your Gift Level.",
  },
  {
    id: "stream",
    name: "Stream Level",
    icon: "📡",
    level: 22,
    progress: 75,
    remainingXp: 15200,
    nextLevel: 23,
    color: "#3B82F6",
    gradient: "from-blue-400 to-cyan-500",
    iconSystem: [
      { name: "Bronze Broadcast Tower", icon: "📡" },
      { name: "Silver Broadcast Tower", icon: "🗼" },
      { name: "Gold Broadcast Tower", icon: "🥇" },
      { name: "Diamond Broadcast Tower", icon: "💎" },
      { name: "Galaxy Broadcast Tower", icon: "🌌" },
    ],
    about: "Stream Level measures the popularity and performance of your live streams and party rooms.",
    howToIncrease: ["Receive Gifts", "Increase Viewer Count", "Increase Watch Time", "Receive More Likes", "Receive More Shares", "Host Active Party Rooms"],
    levelRange: "21-30",
    coinsRequired: "20,000,000 Coins",
    description: "Grow your audience, increase engagement, and receive more gifts to level up your stream.",
  },
];