export const collectionConfig = {
  bronze: { name: "Bronze", color: "#B8860B", gradient: "from-amber-500 to-yellow-700", glow: "rgba(184,134,11,0.45)" },
  silver: { name: "Silver", color: "#94A3B8", gradient: "from-slate-300 to-slate-500", glow: "rgba(148,163,184,0.45)" },
  gold: { name: "Gold", color: "#F59E0B", gradient: "from-yellow-400 to-amber-600", glow: "rgba(245,158,11,0.5)" },
  diamond: { name: "Diamond", color: "#22D3EE", gradient: "from-cyan-300 to-blue-500", glow: "rgba(34,211,238,0.5)" },
  royal: { name: "Royal", color: "#A855F7", gradient: "from-purple-500 to-violet-700", glow: "rgba(168,85,247,0.5)" },
  mythic: { name: "Mythic", color: "#EC4899", gradient: "from-pink-500 to-rose-600", glow: "rgba(236,72,153,0.5)" },
  legendary: { name: "Legendary", color: "#EF4444", gradient: "from-red-500 to-orange-600", glow: "rgba(239,68,68,0.5)" },
  ultimate: { name: "Ultimate", color: "#6366F1", gradient: "from-indigo-500 via-purple-500 to-pink-500", glow: "rgba(99,102,241,0.6)" },
};

export const userLevelTiers = [
  {
    tier: 1, collection: "bronze", icon: "🛡️",
    name: "Rising Spark Collection", levels: "LV1–LV10", coins: "1,500,000",
    badge: "Bronze Crystal Shield",
    description: "New users beginning their journey on VYRO LIVE CONNECT.",
    benefits: ["Starter Profile Frame", "Basic Chat Bubble", "Daily Login Bonus", "New User Badge"],
    rewards: ["Bronze Frame", "Starter Bubble", "Daily Reward Box", "New User Badge"],
    unlock: "Bronze Spark Explosion",
  },
  {
    tier: 2, collection: "bronze", icon: "👑",
    name: "Social Explorer Collection", levels: "LV11–LV20", coins: "4,000,000",
    badge: "Bronze Crown",
    description: "Active users exploring the social universe of VYRO.",
    benefits: ["Bronze Profile Frame", "Enhanced XP Rewards", "Explorer Badge", "Special Emoji Pack"],
    rewards: ["Bronze Frame", "Explorer Badge", "Emoji Pack", "XP Booster"],
    unlock: "Bronze Crown Evolution",
  },
  {
    tier: 3, collection: "silver", icon: "🛡️",
    name: "Silver Guardian Collection", levels: "LV21–LV30", coins: "8,000,000",
    badge: "Silver Shield Crown",
    description: "Dedicated members gaining silver-tier recognition.",
    benefits: ["Silver Frame", "Username Highlight", "VIP Entry Animation", "Daily Reward Boost"],
    rewards: ["Silver Frame", "VIP Entrance Effect", "Username Glow", "Reward Chest"],
    unlock: "Silver Crystal Burst",
  },
  {
    tier: 4, collection: "silver", icon: "🎖️",
    name: "Silver Commander Collection", levels: "LV31–LV40", coins: "15,000,000",
    badge: "Royal Silver Crest",
    description: "Commanders leading with enhanced presence and prestige.",
    benefits: ["Commander Badge", "Advanced Chat Bubble", "Enhanced Visibility", "Extra Rewards"],
    rewards: ["Commander Badge", "Premium Bubble", "Visibility Boost", "Reward Chest"],
    unlock: "Commander Ascension",
  },
  {
    tier: 5, collection: "silver", icon: "👑",
    name: "Silver Emperor Collection", levels: "LV41–LV50", coins: "25,000,000",
    badge: "Silver Imperial Crown",
    description: "Emperors of the silver tier with premium privileges.",
    benefits: ["Premium Frame", "VIP Welcome Effect", "Silver Username Color", "Achievement Rewards"],
    rewards: ["Imperial Frame", "Welcome Animation", "Username Effect", "Achievement Trophy"],
    unlock: "Silver Emperor Rise",
  },
  {
    tier: 6, collection: "gold", icon: "⚔️",
    name: "Golden Knight Collection", levels: "LV51–LV60", coins: "40,000,000",
    badge: "Golden Knight Crest",
    description: "Valiant knights entering the golden ranks.",
    benefits: ["Gold Username", "Premium Bubble", "Party Room Priority", "Knight Achievement"],
    rewards: ["Gold Frame", "Knight Badge", "Premium Bubble", "Gold Trophy"],
    unlock: "Knight Valor",
  },
  {
    tier: 7, collection: "gold", icon: "🏆",
    name: "Golden Champion Collection", levels: "LV61–LV70", coins: "65,000,000",
    badge: "Gold Champion Crown",
    description: "Champions celebrated across the golden arena.",
    benefits: ["Gold Crown Badge", "Bonus Rewards", "Exclusive Events", "Priority Features"],
    rewards: ["Champion Crown", "Gold Medal", "Event Pass", "Priority Badge"],
    unlock: "Champion Glory",
  },
  {
    tier: 8, collection: "gold", icon: "🎓",
    name: "Golden Master Collection", levels: "LV71–LV80", coins: "100,000,000",
    badge: "Golden Master Seal",
    description: "Masters of the craft with elite golden status.",
    benefits: ["Elite Chat Bubble", "Special Entrance", "Gold Frame", "Reward Multiplier"],
    rewards: ["Master Frame", "Elite Bubble", "Entrance Effect", "Multiplier Token"],
    unlock: "Master Ascension",
  },
  {
    tier: 9, collection: "gold", icon: "📜",
    name: "Golden Legend Collection", levels: "LV81–LV90", coins: "150,000,000",
    badge: "Legendary Gold Scroll",
    description: "Legends etched into golden history.",
    benefits: ["Legendary Badge", "Premium Rewards", "Special Animations", "Exclusive Access"],
    rewards: ["Legend Badge", "Premium Pack", "Animation Set", "Access Key"],
    unlock: "Legend Awakening",
  },
  {
    tier: 10, collection: "gold", icon: "👑",
    name: "Golden Supreme Collection", levels: "LV91–LV100", coins: "220,000,000",
    badge: "Supreme Gold Crown",
    description: "Supreme rulers of the golden era.",
    benefits: ["Supreme Crown", "Premium Decorations", "VIP Features", "Gold Prestige Status"],
    rewards: ["Supreme Crown", "Decoration Pack", "VIP Pass", "Prestige Medal"],
    unlock: "Supreme Coronation",
  },
  {
    tier: 11, collection: "diamond", icon: "💎",
    name: "Diamond Elite Collection", levels: "LV101–LV110", coins: "350,000,000",
    badge: "Diamond Elite Badge",
    description: "Elite members stepping into the diamond realm.",
    benefits: ["Diamond Profile Frame", "Diamond Username", "Exclusive Avatar Border", "Premium Entrance Animation"],
    rewards: ["Diamond Frame", "Diamond Name", "Avatar Border", "Entrance Effect"],
    unlock: "Diamond Brilliance",
  },
  {
    tier: 12, collection: "diamond", icon: "🦸",
    name: "Diamond Hero Collection", levels: "LV111–LV120", coins: "350,000,000",
    badge: "Diamond Hero Crest",
    description: "Heroes shining with diamond brilliance.",
    benefits: ["Hero Badge", "Diamond Glow Effect", "Enhanced Rewards", "Elite Recognition"],
    rewards: ["Hero Badge", "Glow Effect", "Reward Bundle", "Elite Medal"],
    unlock: "Hero Radiance",
  },
  {
    tier: 13, collection: "diamond", icon: "🏛️",
    name: "Diamond Lord Collection", levels: "LV121–LV130", coins: "600,000,000",
    badge: "Diamond Lord Scepter",
    description: "Lords commanding the diamond domain.",
    benefits: ["Diamond VIP Status", "Premium Nameplate", "Special Access Rights", "Luxury Effects"],
    rewards: ["VIP Status", "Nameplate", "Access Pass", "Luxury Effects"],
    unlock: "Lord Coronation",
  },
  {
    tier: 14, collection: "diamond", icon: "🤴",
    name: "Diamond King Collection", levels: "LV131–LV140", coins: "600,000,000",
    badge: "Diamond King Crown",
    description: "Kings of the diamond kingdom.",
    benefits: ["King Badge", "Diamond Entrance Effect", "Monthly Rewards", "Elite Collection"],
    rewards: ["King Crown", "Entrance Effect", "Monthly Chest", "Elite Pack"],
    unlock: "King Ascension",
  },
  {
    tier: 15, collection: "diamond", icon: "👑",
    name: "Diamond Emperor Collection", levels: "LV141–LV150", coins: "1,000,000,000",
    badge: "Diamond Imperial Crown",
    description: "Emperors reigning over diamond prestige.",
    benefits: ["Emperor Status", "Advanced Profile Effects", "Exclusive Content", "Premium Gifts"],
    rewards: ["Emperor Crown", "Profile Effects", "Content Pass", "Premium Gifts"],
    unlock: "Emperor Rise",
  },
  {
    tier: 16, collection: "royal", icon: "🎖️",
    name: "Royal Noble Collection", levels: "LV151–LV160", coins: "1,000,000,000",
    badge: "Royal Noble Crest",
    description: "Nobles entering the royal court.",
    benefits: ["Royal Frame", "Royal Decorations", "Premium Visibility", "Exclusive Privileges"],
    rewards: ["Royal Frame", "Decorations", "Visibility Boost", "Privilege Pass"],
    unlock: "Noble Investiture",
  },
  {
    tier: 17, collection: "royal", icon: "🏅",
    name: "Royal Duke Collection", levels: "LV161–LV170", coins: "1,700,000,000",
    badge: "Royal Duke Seal",
    description: "Dukes wielding royal authority.",
    benefits: ["Duke Badge", "VIP Access", "Monthly Bonuses", "Royal Rewards"],
    rewards: ["Duke Badge", "VIP Pass", "Bonus Chest", "Royal Rewards"],
    unlock: "Duke Ennoblement",
  },
  {
    tier: 18, collection: "royal", icon: "🐉",
    name: "Royal King Collection", levels: "LV171–LV180", coins: "1,700,000,000",
    badge: "Royal Dragon Crown",
    description: "Kings accompanied by dragon effects.",
    benefits: ["Dragon Effects", "Royal Entrance", "Premium Collection", "Event Invitations"],
    rewards: ["Dragon Effect", "Royal Entrance", "Collection Set", "Event Invite"],
    unlock: "Dragon Awakening",
  },
  {
    tier: 19, collection: "royal", icon: "👑",
    name: "Royal Emperor Collection", levels: "LV181–LV190", coins: "3,000,000,000",
    badge: "Royal Emperor Crown",
    description: "Emperors of the royal dynasty.",
    benefits: ["Emperor Crown", "Royal Username", "Exclusive Gifts", "Elite Access"],
    rewards: ["Emperor Crown", "Username Effect", "Gift Set", "Elite Access"],
    unlock: "Imperial Ascension",
  },
  {
    tier: 20, collection: "royal", icon: "🦅",
    name: "Royal Sovereign Collection", levels: "LV191–LV200", coins: "3,000,000,000",
    badge: "Sovereign Royal Emblem",
    description: "Sovereign rulers with supreme royal command.",
    benefits: ["Sovereign Status", "Exclusive Decorations", "VIP+ Access", "Special Rewards"],
    rewards: ["Sovereign Badge", "Decorations", "VIP+ Pass", "Reward Chest"],
    unlock: "Sovereign Rise",
  },
  {
    tier: 21, collection: "mythic", icon: "⚔️",
    name: "Mythic Warrior Collection", levels: "LV201–LV210", coins: "5,000,000,000",
    badge: "Mythic Warrior Blade",
    description: "Warriors of mythic legend.",
    benefits: ["Mythic Frame", "Mythic Effects", "Event Access", "Monthly Rewards"],
    rewards: ["Mythic Frame", "Effect Pack", "Event Pass", "Monthly Chest"],
    unlock: "Warrior Manifestation",
  },
  {
    tier: 22, collection: "mythic", icon: "🏆",
    name: "Mythic Champion Collection", levels: "LV211–LV220", coins: "5,000,000,000",
    badge: "Mythic Champion Crown",
    description: "Champions of the mythic order.",
    benefits: ["Champion Badge", "Premium Rewards", "VIP Recognition", "Elite Access"],
    rewards: ["Champion Crown", "Reward Pack", "VIP Badge", "Elite Pass"],
    unlock: "Champion Glory",
  },
  {
    tier: 23, collection: "mythic", icon: "🗿",
    name: "Mythic Titan Collection", levels: "LV221–LV230", coins: "8,000,000,000",
    badge: "Mythic Titan Monument",
    description: "Titans towering over the mythic realm.",
    benefits: ["Titan Status", "Rare Cosmetics", "Event Priority", "Enhanced Features"],
    rewards: ["Titan Badge", "Cosmetics Pack", "Priority Pass", "Feature Boost"],
    unlock: "Titan Awakening",
  },
  {
    tier: 24, collection: "mythic", icon: "👁️",
    name: "Mythic Overlord Collection", levels: "LV231–LV240", coins: "8,000,000,000",
    badge: "Mythic Overlord Sigil",
    description: "Overlords commanding mythic dominion.",
    benefits: ["Overlord Badge", "Premium Animations", "Priority Support", "Exclusive Access"],
    rewards: ["Overlord Badge", "Animation Set", "Support Pass", "Access Key"],
    unlock: "Overlord Dominion",
  },
  {
    tier: 25, collection: "mythic", icon: "✨",
    name: "Mythic Supreme Collection", levels: "LV241–LV250", coins: "13,000,000,000",
    badge: "Mythic Supreme Crown",
    description: "Supreme beings of the mythic tier.",
    benefits: ["Supreme Status", "Luxury Collection", "Global Recognition", "Rare Rewards"],
    rewards: ["Supreme Crown", "Luxury Pack", "Recognition Badge", "Rare Rewards"],
    unlock: "Supreme Ascension",
  },
  {
    tier: 26, collection: "legendary", icon: "🐲",
    name: "Legendary Dragon Collection", levels: "LV251–LV260", coins: "13,000,000,000",
    badge: "Legendary Dragon Badge",
    description: "Dragon-bound legends of the realm.",
    benefits: ["Legendary Dragon Badge", "Premium Invitations", "Rare Gifts", "Elite Rewards"],
    rewards: ["Dragon Badge", "Invitation Pass", "Rare Gifts", "Elite Chest"],
    unlock: "Dragon Descent",
  },
  {
    tier: 27, collection: "legendary", icon: "🌋",
    name: "Legendary Titan Collection", levels: "LV261–LV270", coins: "20,000,000,000",
    badge: "Legendary Titan Emblem",
    description: "Titans of legendary scale.",
    benefits: ["Titan Status", "Special Privileges", "Exclusive Access", "Event Priority"],
    rewards: ["Titan Emblem", "Privilege Pass", "Access Key", "Priority Badge"],
    unlock: "Titan Forge",
  },
  {
    tier: 28, collection: "legendary", icon: "⚡",
    name: "Legendary Overlord Collection", levels: "LV271–LV280", coins: "20,000,000,000",
    badge: "Legendary Overlord Crown",
    description: "Overlords of legendary reign.",
    benefits: ["Overlord Collection", "VIP+ Features", "Special Recognition", "Luxury Rewards"],
    rewards: ["Overlord Crown", "VIP+ Pass", "Recognition Medal", "Luxury Chest"],
    unlock: "Overlord Reign",
  },
  {
    tier: 29, collection: "legendary", icon: "🌌",
    name: "Legendary Universe King Collection", levels: "LV281–LV290", coins: "28,000,000,000",
    badge: "Universe King Crown",
    description: "Kings of the universal expanse.",
    benefits: ["Universe Frame", "Cosmic Effects", "Global Access", "Annual Rewards"],
    rewards: ["Universe Frame", "Cosmic Effect", "Global Pass", "Annual Chest"],
    unlock: "Universe Coronation",
  },
  {
    tier: 30, collection: "legendary", icon: "🌠",
    name: "Legendary Universe Emperor Collection", levels: "LV291–LV299", coins: "40,000,000,000",
    badge: "Universe Emperor Crown",
    description: "Emperors of the legendary universe.",
    benefits: ["Emperor Recognition", "Exclusive Cosmetics", "Global Prestige", "Ultimate Rewards"],
    rewards: ["Emperor Crown", "Cosmetics Pack", "Prestige Medal", "Ultimate Chest"],
    unlock: "Universe Emperor Rise",
  },
  {
    tier: 31, collection: "ultimate", icon: "👑",
    name: "Ultimate Universe Emperor", levels: "LV300", coins: "50,000,000,000",
    badge: "Ultimate Cosmic Emperor Crown",
    description: "The supreme LV300 ruler of the entire VYRO universe — the ultimate prestige.",
    benefits: [
      "Exclusive LV300 Emperor Badge",
      "Ultimate Animated Profile Frame",
      "Cosmic Nameplate Animation",
      "Global Leaderboard Highlight",
      "VIP+ Priority Support",
      "Exclusive Annual Rewards",
      "Elite Achievement Collection",
      "Universal Prestige Status",
      "Founder Recognition",
      "Exclusive Gift Effects",
      "Lifetime Prestige Collection",
    ],
    rewards: ["Emperor Crown", "Emperor Frame", "Cosmic Nameplate", "Leaderboard Crown", "Gift Effects", "Prestige Trophy"],
    unlock: "Universal Emperor Ascension",
  },
];

export const currentUserLevel = {
  level: 35,
  username: "VYRO Owner",
  tierName: "Silver Commander",
  badge: "Royal Silver Crest",
  progress: 80,
  xp: 17600,
  xpMax: 88000,
  coins: 12500000,
  rank: "#1,247",
  avatar: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=200&h=200&fit=crop",
};