/**
 * Maps Supabase public-schema tables to React Query key prefixes.
 * When a realtime event arrives for a table, all queries whose key
 * starts with one of the listed prefixes are invalidated (and refetched
 * only if currently observed / active).
 *
 * Only add prefixes that actually match query keys used by the app's hooks
 * (useHomeFeed, useDashboardData, useVipProfile, useSellerDashboard, ...).
 */
export const TABLE_QUERY_MAP = {
  // ── Profiles & users ───────────────────────────────────────────────
  profiles: [["profile"], ["user"], ["dashboard"], ["home"]],
  users: [["user"], ["dashboard"]],
  app_users: [["user"], ["dashboard"]],
  user_profiles: [["profile"], ["user"]],
  UserProfile: [["profile"], ["user"]],
  user_identities: [["profile"], ["user"]],
  global_identity_vw: [["profile"], ["user"]],
  identity_registry: [["profile"], ["user"]],
  ApplicationId: [["profile"], ["verification"], ["application-id"]],
  application_ids: [["profile"], ["verification"], ["application-id"]],
  user_presence: [["user"], ["social"]],
  user_roles: [["user"], ["dashboard"]],
  user_verifications: [["user"], ["profile"], ["verification"]],
  verification_center: [["verification"], ["user"]],

  // ── Level system ───────────────────────────────────────────────────
  user_levels: [["levels"], ["level"], ["profile-stats"]],
  user_xp: [["levels"], ["profile-stats"]],
  user_rewards: [["rewards"], ["levels"]],
  user_badges: [["badges"], ["profile-stats"], ["achievements"]],
  user_achievements: [["achievements"], ["profile-stats"]],
  user_collections: [["collections"], ["levels"]],
  user_level_equipment: [["levels"], ["equipment"]],
  level_transactions: [["levels"], ["history"]],
  level_reward_claims: [["rewards"], ["levels"]],
  host_levels: [["levels"], ["host"], ["level"]],
  host_level_stats: [["levels"], ["host"]],
  host_rewards: [["rewards"], ["host"]],
  host_achievements: [["achievements"], ["host"]],
  host_level_equipment: [["levels"], ["host"]],
  gifting_levels: [["levels"], ["gifting"]],
  gifting_rewards: [["rewards"], ["gifting"]],
  gifting_achievements: [["achievements"], ["gifting"]],
  gifting_level_equipment: [["levels"], ["gifting"]],
  stream_levels: [["levels"], ["streaming"]],
  streaming_level_stats: [["levels"], ["streaming"]],
  stream_rewards: [["rewards"], ["streaming"]],
  stream_achievements: [["achievements"], ["streaming"]],
  streaming_level_equipment: [["levels"], ["streaming"]],
  level_guides: [["levels"], ["level-guide"]],

  // ── Wallet & coins ─────────────────────────────────────────────────
  wallet: [["wallet"], ["finance"], ["coins"]],
  wallets: [["wallet"], ["finance"]],
  user_wallets: [["wallet"], ["finance"]],
  coin_wallets: [["coins"], ["wallet"]],
  wallet_accounts: [["wallet"], ["finance"]],
  wallet_ledger: [["wallet"], ["finance"], ["transactions"]],
  wallet_transactions: [["transactions"], ["wallet"], ["finance"]],
  coin_ledger: [["coins"], ["transactions"]],
  coin_purchases: [["coins"], ["transactions"]],
  coin_transfers: [["coins"], ["transactions"]],
  seller_recharges: [["seller"], ["ocs"], ["transactions"]],

  // ── VIP ────────────────────────────────────────────────────────────
  vip_memberships: [["vip"]],
  user_vip_memberships: [["vip"]],
  user_vip_status: [["vip"]],
  vip_profiles: [["vip"]],
  vip_levels: [["vip"]],
  vip_tiers: [["vip"]],
  vip_plans: [["vip"]],
  vip_rewards: [["vip"], ["rewards"]],
  vip_daily_rewards: [["vip"], ["rewards"]],
  vip_transactions: [["vip"], ["transactions"]],
  vip_membership_changes: [["vip"]],

  // ── Rooms & streaming ─────────────────────────────────────────────
  rooms: [["rooms"], ["party"], ["live"], ["home"]],
  live_rooms: [["live"], ["live-room"], ["liveRoom"], ["rooms"]],
  voice_rooms: [["rooms"], ["live"]],
  party_rooms: [["party"], ["rooms"], ["home"]],
  room_participants: [["live-room"], ["liveRoom"], ["rooms"]],
  room_members: [["live-room"], ["rooms"]],
  room_seats: [["live-room"], ["liveRoom"], ["rooms"]],
  room_mic_requests: [["live-room"], ["liveRoom"]],
  room_speak_requests: [["live-room"], ["liveRoom"]],
  room_voice_status: [["live-room"], ["liveRoom"]],
  active_speakers: [["live-room"], ["liveRoom"]],
  room_messages: [["live-room"], ["liveRoom"], ["messages"]],
  room_gifts: [["live-room"], ["liveRoom"], ["gifts"]],
  room_settings: [["live-room"], ["liveRoom"], ["rooms"]],
  live_sessions: [["live"], ["live-room"], ["liveRoom"]],

  // ── Messages & social ──────────────────────────────────────────────
  messages: [["messages"], ["chat"]],
  chats: [["messages"], ["chat"]],
  group_messages: [["messages"], ["chat"]],
  follows: [["social"]],
  friends: [["social"]],
  relationships: [["social"]],
  relationship_requests: [["social"]],
  blocked_users: [["social"]],
  blocks: [["social"]],
  post_comments: [["community"]],
  post_likes: [["community"]],
  post_shares: [["community"]],
  community_posts: [["community"]],

  // ── Notifications ──────────────────────────────────────────────────
  notifications: [["notifications"], ["notification"]],
  message_notifications: [["notifications"], ["messages"]],
  application_notifications: [["notifications"]],
  relationship_notifications: [["notifications"], ["social"]],
  room_notifications: [["notifications"], ["live-room"]],
  seller_notifications: [["notifications"], ["seller"]],
  notification_delivery_queue: [["notifications"]],

  // ── Gifts, events, PK, leaderboards ───────────────────────────────
  gift_transactions: [["gifts"], ["transactions"], ["wallet"]],
  global_gift_announcements: [["gifts"]],
  events: [["events"]],
  event_participants: [["events"]],
  event_rankings: [["events"], ["leaderboard"]],
  pk_battles: [["pk"]],
  pk_requests: [["pk"]],
  pk_tournaments: [["pk"]],
  leaderboards: [["leaderboard"], ["leaderboards"]],
  user_leaderboard: [["leaderboard"], ["leaderboards"]],
  host_leaderboard: [["leaderboard"], ["leaderboards"]],
  gifting_leaderboard: [["leaderboard"], ["leaderboards"]],
  stream_leaderboard: [["leaderboard"], ["leaderboards"]],

  // ── Tasks & rewards ───────────────────────────────────────────────
  tasks: [["tasks"], ["tasks-rewards"]],
  rewards: [["rewards"], ["tasks-rewards"]],

  // ── Mall & purchases ──────────────────────────────────────────────
  mall_items: [["mall"], ["mall-items"]],
  user_purchases: [["mall"], ["purchases"]],

  // ── Seller / OCS ──────────────────────────────────────────────────
  seller_applications: [["seller"], ["ocs"]],
  seller_packages: [["seller"], ["ocs"]],
  seller_earnings: [["seller"], ["ocs"]],
  seller_analytics: [["seller"], ["ocs"]],
  seller_customers: [["seller"], ["ocs"]],

  // ── Agencies / agents / hosts ──────────────────────────────────────
  agencies: [["agency"]],
  agents: [["agent"]],
  hosts: [["host"]],

  // ── Trust & reputation ────────────────────────────────────────────
  warnings: [["trust"], ["reputation"], ["trust-reputation"]],
  appeals: [["trust"], ["reputation"], ["trust-reputation"]],
  reports: [["trust"], ["reputation"], ["reports"], ["support"]],
  reputation_history: [["trust"], ["reputation"], ["trust-reputation"]],

  // ── Verification ──────────────────────────────────────────────────
  verification_records: [["verification"]],

  // ── Security / moderation ────────────────────────────────────────
  security_events: [["security"], ["dashboard"]],
  spam_detections: [["security"], ["spam"]],
  violation_records: [["security"], ["violation"]],
  enforcement_actions: [["security"], ["enforcement"]],
  content_moderation_logs: [["security"], ["content-moderation"]],
  fraud_detections: [["security"], ["fraud"]],
  incidents: [["security"], ["incident"]],
  audit_logs: [["audit"], ["security"]],
  device_records: [["security"], ["device"]],

  // ── Dashboard registry (Creator Center control tables) ─────────────
  creator_center: [["dashboard-registry"], ["dashboard"]],
  creator_center_dashboards: [["dashboard-registry"], ["dashboard"]],
  dashboard_registry: [["dashboard-registry"]],
  dashboard_access_matrix: [["dashboard-registry"], ["dashboard"]],
  role_access_matrix: [["dashboard-registry"]],
  role_permissions: [["dashboard-registry"]],
  role_module_access: [["dashboard-registry"]],
  user_role_identities: [["dashboard-registry"], ["user"]],
  vyro_role_ids: [["dashboard-registry"], ["user"]],
  dashboard_action_registry: [["dashboard-registry"], ["dashboard"]],

  // ── Invites / friends / support / settings ────────────────────────
  invites: [["social"]],
  friend_requests: [["social"]],
  support_tickets: [["support"]],
  app_settings: [["settings"]],
  notification_settings: [["settings"], ["notifications"]],
  privacy_settings: [["settings"], ["privacy"]],
  security_settings: [["settings"], ["security"]],
  device_settings: [["settings"], ["device"]],

  // ── Dashboard module tables (normalized registry source tables) ────
  admin_dashboard_modules: [["dashboard-registry"], ["admin"]],
  sam_dashboard_modules: [["dashboard-registry"], ["sam"]],
  vip_manager_dashboard_modules: [["dashboard-registry"], ["vip-manager"]],
  bd_dashboard_modules: [["dashboard-registry"], ["business-developer"]],
  bm_dashboard_modules: [["dashboard-registry"], ["business-manager"]],
  reward_dashboard_modules: [["dashboard-registry"], ["reward-manager"]],
  support_dashboard_modules: [["dashboard-registry"], ["support-manager"]],
  marketing_dashboard_modules: [["dashboard-registry"], ["marketing-manager"]],
  event_dashboard_modules: [["dashboard-registry"], ["event-manager"]],
  pk_dashboard_modules: [["dashboard-registry"], ["pk-manager"]],
  finance_dashboard_modules: [["dashboard-registry"], ["finance-manager"]],

  // ── Admin dashboard data ──────────────────────────────────────────
  admin_actions_log: [["admin"], ["audit"]],
  admin_assignments: [["admin"]],
  admin_kpis: [["admin"]],
  admin_tasks: [["admin"]],

  // ── SAM dashboard data ────────────────────────────────────────────
  coin_sales: [["sam"], ["coins"]],
  coin_sellers: [["sam"], ["seller"]],
  coin_seller_applications: [["sam"], ["seller"]],
  coin_recharge_packages: [["sam"], ["coins"]],
  offline_recharge_requests: [["sam"], ["seller"]],
  withdraw_requests: [["sam"], ["finance"]],
  withdrawals: [["sam"], ["finance"]],
  wallet_control_state: [["sam"], ["wallet"]],
  commission_rules: [["sam"], ["finance"]],
  commission_transactions: [["sam"], ["finance"]],
  commission_settlements: [["sam"], ["finance"]],
  commission_wallet: [["sam"], ["finance"]],
  global_payments: [["sam"], ["finance"]],
  global_revenue: [["sam"], ["finance"]],
  revenue_ledger: [["sam"], ["finance"]],
  payment_intents: [["sam"], ["finance"]],

  // ── VIP manager data ──────────────────────────────────────────────
  vip_assets: [["vip-manager"]],
  vip_benefits: [["vip-manager"]],
  vip_communications: [["vip-manager"]],
  vip_events: [["vip-manager"], ["vip"]],
  vip_event_participants: [["vip-manager"], ["vip"]],
  vip_partnerships: [["vip-manager"]],
  vip_rankings: [["vip-manager"], ["vip"]],
  vip_reports: [["vip-manager"]],
  vip_retention_metrics: [["vip-manager"]],
  vip_revenue_analytics: [["vip-manager"]],
  vip_reward_distributions: [["vip-manager"], ["vip"]],
  vip_settings: [["vip-manager"]],
  vip_team_members: [["vip-manager"]],
  vip_ai_predictions: [["vip-manager"], ["vip"]],
  vip_manager_campaigns: [["vip-manager"]],
  vip_manager_member_actions: [["vip-manager"]],
  vip_manager_report_jobs: [["vip-manager"]],
  vip_manager_settings: [["vip-manager"]],
  vip_manager_tasks: [["vip-manager"]],

  // ── Business developer data ─────────────────────────────────────
  bd_leads: [["business-developer"]],
  bd_partnerships: [["business-developer"]],
  bd_expansion_plans: [["business-developer"]],
  bd_targets: [["business-developer"]],
  bd_tasks: [["business-developer"]],
  bd_settings: [["business-developer"]],

  // ── Business manager data ───────────────────────────────────────
  bm_targets: [["business-manager"]],
  bm_tasks: [["business-manager"]],
  bm_team_members: [["business-manager"]],

  // ── Reward manager data ─────────────────────────────────────────
  reward_programs: [["reward-manager"]],
  reward_reports: [["reward-manager"]],
  reward_settings: [["reward-manager"]],
  reward_claims: [["reward-manager"], ["rewards"]],
  reward_distributions: [["reward-manager"], ["rewards"]],
  reward_fraud_reviews: [["reward-manager"]],
  reward_leaderboards: [["reward-manager"], ["leaderboard"]],
  reward_team_members: [["reward-manager"]],
  reward_ai_predictions: [["reward-manager"]],
  reward_manager_assignments: [["reward-manager"]],
  reward_manager_campaigns: [["reward-manager"]],
  reward_manager_fraud_cases: [["reward-manager"]],
  reward_manager_report_jobs: [["reward-manager"]],
  reward_manager_settings: [["reward-manager"]],
  reward_manager_tasks: [["reward-manager"]],
  bonus_campaigns: [["reward-manager"]],
  loyalty_programs: [["reward-manager"]],
  loyalty_points: [["reward-manager"]],
  coin_reward_transactions: [["reward-manager"], ["coins"]],
  referral_stats: [["reward-manager"]],
  referrals: [["reward-manager"]],

  // ── Support manager data ────────────────────────────────────────
  support_cases: [["support-manager"], ["support"]],
  support_categories: [["support-manager"]],
  support_escalations: [["support-manager"]],
  support_feedback: [["support-manager"]],
  support_logs: [["support-manager"]],
  support_messages: [["support-manager"], ["messages"]],
  support_sla_policies: [["support-manager"]],
  support_staff: [["support-manager"]],
  support_manager_report_jobs: [["support-manager"]],
  support_manager_settings: [["support-manager"]],
  support_manager_tasks: [["support-manager"]],

  // ── Marketing manager data ──────────────────────────────────────
  marketing_campaigns: [["marketing-manager"]],
  marketing_content: [["marketing-manager"]],
  marketing_promotions: [["marketing-manager"]],
  marketing_metrics: [["marketing-manager"]],
  marketing_staff_shifts: [["marketing-manager"]],
  marketing_brand_assets: [["marketing-manager"]],
  marketing_communications: [["marketing-manager"]],
  marketing_influencer_collaborations: [["marketing-manager"]],
  marketing_ai_insights: [["marketing-manager"]],
  marketing_manager_events: [["marketing-manager"]],
  marketing_manager_report_jobs: [["marketing-manager"]],
  marketing_manager_settings: [["marketing-manager"]],
  marketing_manager_tasks: [["marketing-manager"]],
  ad_campaigns: [["marketing-manager"]],
  social_media_posts: [["marketing-manager"]],
  influencers: [["marketing-manager"]],

  // ── Event manager data ──────────────────────────────────────────
  event_operations: [["event-manager"]],
  event_reports: [["event-manager"]],
  event_revenue: [["event-manager"]],
  event_rewards: [["event-manager"]],
  event_settings: [["event-manager"]],
  event_staff: [["event-manager"]],
  event_competitions: [["event-manager"]],
  event_communications: [["event-manager"]],
  event_ai_predictions: [["event-manager"]],
  event_registration_reviews: [["event-manager"]],
  event_reward_assignments: [["event-manager"]],
  event_manager_report_jobs: [["event-manager"]],
  event_manager_settings: [["event-manager"]],
  event_manager_tasks: [["event-manager"]],

  // ── PK manager data ─────────────────────────────────────────────
  pk_operations: [["pk-manager"]],
  pk_reports: [["pk-manager"]],
  pk_disputes: [["pk-manager"]],
  pk_fair_play_cases: [["pk-manager"]],
  pk_reward_definitions: [["pk-manager"]],
  pk_reward_assignments: [["pk-manager"]],
  pk_tournament_matches: [["pk-manager"]],
  pk_manager_settings: [["pk-manager"]],
  pk_manager_staff: [["pk-manager"]],
  pk_manager_tasks: [["pk-manager"]],
  pk_report_jobs: [["pk-manager"]],

  // ── Finance manager data ───────────────────────────────────────
  finance_manager_audit_cases: [["finance-manager"]],
  finance_manager_fraud_cases: [["finance-manager"]],
  finance_manager_report_jobs: [["finance-manager"]],
  finance_manager_settings: [["finance-manager"]],
  finance_manager_tasks: [["finance-manager"]],
  fraud_flags: [["finance-manager"], ["fraud"]],
  gift_commission_allocations: [["finance-manager"], ["gifts"]],

  // ── Agency / agent / host data ─────────────────────────────────
  agency_campaigns: [["agency"]],
  agency_earnings: [["agency"]],
  agency_hosts: [["agency"]],
  agency_invites: [["agency"]],
  agency_members: [["agency"]],
  agency_revenue: [["agency"]],
  agency_settings: [["agency"]],
  agent_communications: [["agent"]],
  agent_dashboard_events: [["agent"]],
  agent_dashboard_settings: [["agent"]],
  agent_dashboard_tasks: [["agent"]],
  agent_earnings: [["agent"]],
  agent_host_assignments: [["agent"]],
  agent_host_targets: [["agent"]],
  agent_host_warnings: [["agent"]],
  agent_report_jobs: [["agent"]],
  host_agency: [["host"], ["agency"]],
  host_analytics: [["host"]],
  host_dashboard_settings: [["host"]],
  host_earnings: [["host"]],
  host_events: [["host"], ["events"]],
  host_history: [["host"]],
  host_profiles: [["host"]],
  host_sessions: [["host"]],
  host_statistics: [["host"]],
  host_targets: [["host"]],
  host_achievements: [["host"], ["achievements"]],

  // ── Achievements / gifts / analytics ────────────────────────────
  achievements: [["achievements"], ["profile-stats"]],
  gifts: [["gifts"]],
  gifting_analytics: [["gifting"], ["analytics"]],

  // ── Country / enterprise data ───────────────────────────────────
  country_kpis: [["country-manager"]],
  country_reward_analytics: [["country-manager"], ["reward-manager"]],
  country_vip_analytics: [["country-manager"], ["vip-manager"]],
  enterprise_revenue_ai: [["dashboard"]],

  // ── Room / audience / moderation data ──────────────────────────
  room_analytics: [["live-room"], ["analytics"]],
  room_audience: [["live-room"]],
  room_moderation: [["live-room"], ["security"]],
  room_reports: [["live-room"]],
  room_stats: [["live-room"]],
  seat_history: [["live-room"]],
  seat_requests: [["live-room"]],

  // ── User activity / device / verification ───────────────────────
  user_activity_events: [["user"]],
  user_dashboard_settings: [["user"]],
  user_tasks: [["user"], ["tasks"]],
  device_logs: [["device"], ["security"]],
  login_history: [["user"], ["security"]],
  verification_requests: [["verification"]],
  role_applications: [["role-application"]],
  role_application_steps: [["role-application"]],

  // ── Owner control ──────────────────────────────────────────────
  owner_control_events: [["dashboard"]],
};