export const AGENCY_INFO = {
  agency_id: "AGY-2026-0042",
  agency_name: "VYRO Elite Agency",
  agency_level: 8,
  verification_status: "Verified",
  agency_rank: 4,
  total_hosts: 247,
  active_hosts: 189,
  monthly_revenue: 485000,
  performance_score: 94.2,
  growth_rate: 12.5,
  region: "Global",
  established: "Jan 2025",
};

export const AGENCY_STATS = [
  { label: "Total Hosts", value: "247", icon: "Users", color: "#8B5CF6", trend: "+8 this month" },
  { label: "Active Hosts", value: "189", icon: "UserCheck", color: "#10B981", trend: "76.5% active" },
  { label: "Inactive Hosts", value: "58", icon: "UserX", color: "#EF4444", trend: "23.5% inactive" },
  { label: "New Recruits", value: "12", icon: "UserPlus", color: "#3B82F6", trend: "This month" },
  { label: "Agency Revenue", value: "$485K", icon: "DollarSign", color: "#D4AF37", trend: "+15.2% YoY" },
  { label: "Commission Earnings", value: "$97K", icon: "Percent", color: "#F59E0B", trend: "20% rate" },
  { label: "Monthly Revenue", value: "$48.5K", icon: "TrendingUp", color: "#059669", trend: "+5.3% MoM" },
  { label: "Performance Score", value: "94.2", icon: "Gauge", color: "#8B5CF6", trend: "Excellent" },
  { label: "Recruitment Success", value: "78%", icon: "Target", color: "#EC4899", trend: "+3% improvement" },
  { label: "Global Agency Rank", value: "#4", icon: "Globe", color: "#1D4ED8", trend: "Top 5 globally" },
  { label: "Regional Rank", value: "#2", icon: "MapPin", color: "#7C3AED", trend: "Asia-Pacific" },
  { label: "Growth Rate", value: "12.5%", icon: "ArrowUpRight", color: "#10B981", trend: "Steady growth" },
];

export const AGENCY_MODULES = [
  {
    id: "agency_overview",
    title: "Agency Overview",
    icon: "Building2",
    color: "#8B5CF6",
    gradient: "linear-gradient(135deg, #7C3AED, #8B5CF6)",
    description: "Agency profile, level, verification, and key metrics",
    features: [
      { label: "Agency ID", value: "AGY-2026-0042", icon: "Hash" },
      { label: "Agency Level", value: "Level 8", icon: "Layers" },
      { label: "Verification Status", value: "Verified", icon: "BadgeCheck", status: "success" },
      { label: "Agency Rank", value: "#4 Global", icon: "Trophy" },
      { label: "Total Hosts", value: "247", icon: "Users" },
      { label: "Active Hosts", value: "189", icon: "UserCheck", status: "success" },
      { label: "Monthly Revenue", value: "$485,000", icon: "DollarSign" },
      { label: "Performance Score", value: "94.2 / 100", icon: "Gauge", status: "success" },
    ],
    actions: [
      { label: "View Agency Profile", icon: "Eye", type: "primary" },
      { label: "Edit Agency Information", icon: "Pencil", type: "secondary" },
    ],
  },
  {
    id: "host_management",
    title: "Host Management",
    icon: "Users",
    color: "#3B82F6",
    gradient: "linear-gradient(135deg, #2563EB, #3B82F6)",
    description: "Manage all hosts across the agency network",
    features: [
      { label: "All Hosts", value: "247", icon: "Users", detail: "Full roster" },
      { label: "Active Hosts", value: "189", icon: "UserCheck", detail: "Currently streaming", status: "success" },
      { label: "Inactive Hosts", value: "58", icon: "UserX", detail: "Not active 7+ days", status: "warning" },
      { label: "New Recruits", value: "12", icon: "UserPlus", detail: "Joined this month" },
      { label: "Top Performers", value: "24", icon: "Star", detail: "Elite tier hosts" },
    ],
    hostList: [
      { name: "Aria Chen", id: "HST-1024", status: "active", level: 12, revenue: 28400, avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100" },
      { name: "Luna Park", id: "HST-1031", status: "active", level: 10, revenue: 22100, avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100" },
      { name: "Sofia Diaz", id: "HST-1038", status: "active", level: 9, revenue: 19500, avatar: "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=100" },
      { name: "Mei Wong", id: "HST-1045", status: "inactive", level: 7, revenue: 8200, avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100" },
      { name: "Yuki Tanaka", id: "HST-1052", status: "active", level: 11, revenue: 24800, avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100" },
    ],
    actions: [
      { label: "Add Host", icon: "UserPlus", type: "primary" },
      { label: "Remove Host", icon: "UserMinus", type: "danger" },
      { label: "Approve Host", icon: "CheckCircle", type: "success" },
      { label: "Suspend Host", icon: "PauseCircle", type: "warning" },
      { label: "Transfer Host", icon: "ArrowRightLeft", type: "secondary" },
    ],
  },
  {
    id: "recruitment_center",
    title: "Recruitment Center",
    icon: "UserPlus",
    color: "#EC4899",
    gradient: "linear-gradient(135deg, #DB2777, #EC4899)",
    description: "Manage applications, candidates, and hiring pipeline",
    features: [
      { label: "Recruitment Applications", value: "34", icon: "FileText", detail: "Pending review" },
      { label: "Candidate Profiles", value: "128", icon: "UserSearch", detail: "In pipeline" },
      { label: "Recruitment Statistics", value: "78%", icon: "BarChart3", detail: "Success rate" },
      { label: "Hiring Pipeline", value: "5 stages", icon: "GitBranch", detail: "Active flow" },
    ],
    pipeline: [
      { stage: "Application Received", count: 34, color: "#3B82F6" },
      { stage: "Initial Screening", count: 22, color: "#8B5CF6" },
      { stage: "Interview Scheduled", count: 15, color: "#EC4899" },
      { stage: "Interview Completed", count: 8, color: "#F59E0B" },
      { stage: "Approved & Onboarded", count: 5, color: "#10B981" },
    ],
    actions: [
      { label: "Approve Application", icon: "CheckCircle", type: "success" },
      { label: "Reject Application", icon: "XCircle", type: "danger" },
      { label: "Schedule Interview", icon: "Calendar", type: "primary" },
      { label: "Send Invitation", icon: "Send", type: "secondary" },
    ],
  },
  {
    id: "revenue_management",
    title: "Revenue Management",
    icon: "DollarSign",
    color: "#D4AF37",
    gradient: "linear-gradient(135deg, #B8941E, #D4AF37)",
    description: "Track agency revenue, commissions, and financial performance",
    features: [
      { label: "Agency Revenue", value: "$485,000", icon: "DollarSign", detail: "All-time total" },
      { label: "Commission Earnings", value: "$97,000", icon: "Percent", detail: "20% commission rate" },
      { label: "Monthly Revenue", value: "$48,500", icon: "Calendar", detail: "Current month" },
      { label: "Revenue Trends", value: "+15.2%", icon: "TrendingUp", detail: "Year over year", status: "success" },
      { label: "Revenue Forecasting", value: "$542K", icon: "LineChart", detail: "Next quarter projection" },
    ],
    revenueBreakdown: [
      { month: "Jan", value: 38 },
      { month: "Feb", value: 41 },
      { month: "Mar", value: 44 },
      { month: "Apr", value: 42 },
      { month: "May", value: 46 },
      { month: "Jun", value: 48.5 },
    ],
    actions: [
      { label: "View Revenue Report", icon: "FileBarChart", type: "primary" },
      { label: "Download Report", icon: "Download", type: "secondary" },
      { label: "Withdraw Earnings", icon: "ArrowDownToLine", type: "success" },
    ],
  },
  {
    id: "performance_analytics",
    title: "Performance Analytics",
    icon: "BarChart3",
    color: "#10B981",
    gradient: "linear-gradient(135deg, #059669, #10B981)",
    description: "Comprehensive analytics across hosts, revenue, and growth",
    features: [
      { label: "Host Performance", value: "94.2 avg", icon: "Gauge", detail: "Across 189 active" },
      { label: "Revenue Analytics", value: "$485K", icon: "DollarSign", detail: "Total tracked" },
      { label: "Growth Analytics", value: "+12.5%", icon: "TrendingUp", detail: "Quarterly growth", status: "success" },
      { label: "Activity Analytics", value: "76.5%", icon: "Activity", detail: "Active rate" },
      { label: "KPI Dashboard", value: "8 / 10", icon: "Target", detail: "KPIs on target", status: "success" },
    ],
    kpis: [
      { name: "Host Retention", value: 92, target: 90, unit: "%" },
      { name: "Revenue Growth", value: 15.2, target: 12, unit: "%" },
      { name: "Recruitment Rate", value: 78, target: 75, unit: "%" },
      { name: "Host Satisfaction", value: 88, target: 85, unit: "%" },
      { name: "Compliance Score", value: 96, target: 95, unit: "%" },
      { name: "Response Time", value: 94, target: 90, unit: "%" },
    ],
    actions: [
      { label: "Export Analytics", icon: "Download", type: "primary" },
      { label: "Generate Reports", icon: "FileText", type: "secondary" },
    ],
  },
  {
    id: "events_campaigns",
    title: "Events & Campaigns",
    icon: "Megaphone",
    color: "#F59E0B",
    gradient: "linear-gradient(135deg, #D97706, #F59E0B)",
    description: "Manage agency events, campaigns, and promotional activities",
    features: [
      { label: "Agency Events", value: "6 active", icon: "Calendar", detail: "Currently running" },
      { label: "Campaign Management", value: "12 total", icon: "Megaphone", detail: "All campaigns" },
      { label: "Reward Campaigns", value: "4 active", icon: "Gift", detail: "Host incentives" },
      { label: "Recruitment Campaigns", value: "3 active", icon: "UserPlus", detail: "Talent acquisition" },
    ],
    campaigns: [
      { name: "Summer Host Challenge", type: "Reward", status: "active", progress: 68, participants: 45 },
      { name: "Q3 Talent Hunt", type: "Recruitment", status: "active", progress: 42, participants: 128 },
      { name: "Top Gifter Bonus Week", type: "Reward", status: "active", progress: 85, participants: 67 },
      { name: "Elite Host Program", type: "Recruitment", status: "ended", progress: 100, participants: 24 },
    ],
    actions: [
      { label: "Create Campaign", icon: "PlusCircle", type: "primary" },
      { label: "Edit Campaign", icon: "Pencil", type: "secondary" },
      { label: "End Campaign", icon: "StopCircle", type: "danger" },
    ],
  },
  {
    id: "compliance_center",
    title: "Compliance Center",
    icon: "ShieldCheck",
    color: "#EF4444",
    gradient: "linear-gradient(135deg, #DC2626, #EF4444)",
    description: "Monitor violations, warnings, and policy compliance",
    features: [
      { label: "Violations", value: "3", icon: "AlertTriangle", detail: "Open cases", status: "warning" },
      { label: "Warnings", value: "7", icon: "AlertCircle", detail: "Issued this month", status: "warning" },
      { label: "Policy Monitoring", value: "Active", icon: "ShieldCheck", detail: "24/7 monitoring", status: "success" },
      { label: "Risk Assessment", value: "Low", icon: "ShieldAlert", detail: "Overall risk level", status: "success" },
    ],
    violations: [
      { host: "Mei Wong", type: "Inactivity", severity: "low", date: "2026-06-28", status: "open" },
      { host: "Kai Lee", type: "Content Violation", severity: "medium", date: "2026-06-25", status: "reviewing" },
      { host: "Nora Kim", type: "Schedule Miss", severity: "low", date: "2026-06-20", status: "resolved" },
    ],
    actions: [
      { label: "Review Violations", icon: "FileSearch", type: "primary" },
      { label: "Submit Appeal", icon: "ScaleIcon", type: "secondary" },
      { label: "Contact Compliance Team", icon: "MessageSquare", type: "secondary" },
    ],
  },
  {
    id: "agency_leaderboard",
    title: "Agency Leaderboard",
    icon: "Trophy",
    color: "#1D4ED8",
    gradient: "linear-gradient(135deg, #1E40AF, #2563EB)",
    description: "Global and regional agency rankings",
    features: [
      { label: "Global Agency Ranking", value: "#4", icon: "Globe", detail: "Out of 1,240 agencies" },
      { label: "Regional Agency Ranking", value: "#2", icon: "MapPin", detail: "Asia-Pacific region" },
      { label: "Revenue Ranking", value: "#3", icon: "DollarSign", detail: "By total revenue" },
      { label: "Growth Ranking", value: "#5", icon: "TrendingUp", detail: "By growth rate" },
    ],
    leaderboard: [
      { rank: 1, name: "Diamond Stars Agency", revenue: 620000, hosts: 312, region: "Global", change: 0 },
      { rank: 2, name: "Phoenix Talent Group", revenue: 580000, hosts: 289, region: "Global", change: 1 },
      { rank: 3, name: "Golden Crown Agency", revenue: 520000, hosts: 265, region: "Global", change: -1 },
      { rank: 4, name: "VYRO Elite Agency", revenue: 485000, hosts: 247, region: "Global", change: 2, isOwn: true },
      { rank: 5, name: "Silver Wave Media", revenue: 440000, hosts: 218, region: "Global", change: 0 },
    ],
    actions: [
      { label: "View Rankings", icon: "ListOrdered", type: "primary" },
      { label: "Compare Performance", icon: "Columns3", type: "secondary" },
    ],
  },
];