export const OCS_REPORT = {
  sellerInfo: {
    title: "Offline Coin Seller (OCS)",
    reportsTo: "Super Admin Manager (SAM) Only",
    position: "Authorized Offline Coin Sales Representative",
  },
  responsibilities: [
    "Sell official VYRO Coin Packages through approved offline channels.",
    "Verify customer payment before coin delivery.",
    "Maintain offline sales records.",
    "Submit daily, weekly, and monthly sales reports.",
    "Prevent fraud and unauthorized coin sales.",
    "Follow company pricing and policies.",
    "Keep customer transaction records.",
    "Coordinate with Finance when required.",
    "Maintain confidentiality of customer information.",
  ],
  authority: {
    may: [
      "Sell only officially approved coin packages.",
      "View personal sales records.",
      "Generate customer invoices.",
      "Submit sales reports.",
      "Request stock allocation (if applicable).",
    ],
    mayNot: [
      "Change coin prices.",
      "Create coin packages.",
      "Modify user balances.",
      "Approve refunds.",
      "Access financial administration.",
    ],
  },
  reportTypes: [
    { id: "daily", name: "Daily Sales Report", icon: "📅", color: "#22D3EE" },
    { id: "weekly", name: "Weekly Sales Report", icon: "📆", color: "#3B82F6" },
    { id: "monthly", name: "Monthly Sales Report", icon: "🗓️", color: "#A855F7" },
    { id: "payment", name: "Customer Payment Report", icon: "💳", color: "#F59E0B" },
    { id: "distribution", name: "Coin Distribution Report", icon: "🪙", color: "#FFD700" },
    { id: "pending", name: "Pending Payment Report", icon: "⏳", color: "#FB923C" },
    { id: "refund", name: "Refund Request Report", icon: "↩️", color: "#EF4444" },
    { id: "fraud", name: "Fraud Report", icon: "🚨", color: "#DC2626" },
    { id: "performance", name: "Sales Performance Report", icon: "📊", color: "#10B981" },
  ],
  reportStatuses: [
    { id: "draft", name: "Draft", color: "#6B7280" },
    { id: "submitted", name: "Submitted", color: "#3B82F6" },
    { id: "review", name: "Under Review", color: "#F59E0B" },
    { id: "approved", name: "Approved", color: "#10B981" },
    { id: "rejected", name: "Rejected", color: "#EF4444" },
    { id: "returned", name: "Returned for Correction", color: "#FB923C" },
    { id: "completed", name: "Completed", color: "#22D3EE" },
  ],
  actions: [
    { id: "create", label: "Create Report", icon: "📝" },
    { id: "save", label: "Save Draft", icon: "💾" },
    { id: "submit", label: "Submit Report", icon: "📤" },
    { id: "edit", label: "Edit Draft", icon: "✏️" },
    { id: "receipt", label: "Upload Receipt", icon: "🧾" },
    { id: "invoice", label: "Upload Invoice", icon: "📄" },
    { id: "screenshot", label: "Upload Screenshot", icon: "🖼️" },
    { id: "excel", label: "Upload Excel File", icon: "📊" },
    { id: "pdf", label: "Upload PDF", icon: "📕" },
    { id: "notes", label: "Add Notes", icon: "🗒️" },
    { id: "submitFinal", label: "Submit", icon: "✅" },
  ],
  dashboardButtons: [
    { label: "Send Report", icon: "📤", path: "send" },
    { label: "View Reports", icon: "👁️", path: "view" },
    { label: "Draft Reports", icon: "📝", path: "draft" },
    { label: "Report History", icon: "📜", path: "history" },
    { label: "Pending Reports", icon: "⏳", path: "pending" },
    { label: "Approved Reports", icon: "✅", path: "approved" },
    { label: "Rejected Reports", icon: "❌", path: "rejected" },
    { label: "Report Analytics", icon: "📈", path: "analytics" },
    { label: "Download PDF", icon: "📕", path: "pdf" },
    { label: "Export Excel", icon: "📊", path: "excel" },
    { label: "Search Reports", icon: "🔍", path: "search" },
    { label: "Filter Reports", icon: "🎛️", path: "filter" },
    { label: "Notification Center", icon: "🔔", path: "notifications" },
  ],
  samCenter: [
    { label: "Offline Coin Seller Reports", icon: "🪙" },
    { label: "Daily Sales Summary", icon: "📅" },
    { label: "Weekly Sales Summary", icon: "📆" },
    { label: "Monthly Sales Summary", icon: "🗓️" },
    { label: "Country-wise Coin Sales", icon: "🌍" },
    { label: "Seller Performance Ranking", icon: "🏆" },
    { label: "Revenue Reports", icon: "💰" },
    { label: "Pending Reports", icon: "⏳" },
    { label: "Approve Report", icon: "✅" },
    { label: "Reject Report", icon: "❌" },
    { label: "Request Correction", icon: "↩️" },
    { label: "Export Reports", icon: "📤" },
    { label: "Audit Log", icon: "📋" },
    { label: "Fraud Detection Reports", icon: "🚨" },
    { label: "Transaction Verification", icon: "🔍" },
    { label: "Sales Analytics Dashboard", icon: "📊" },
  ],
  reports: [
    { id: "RPT-2847", type: "Daily Sales Report", sender: "Premium Seller", role: "OCS", receiver: "Super Admin Manager", receiverRole: "SAM", date: "2026-07-03", time: "14:32", country: "Qatar", department: "Revenue Distribution", status: "approved", statusId: "approved", description: "Daily coin sales summary for July 3", comments: "Verified and approved by SAM", attachments: 3 },
    { id: "RPT-2846", type: "Weekly Sales Report", sender: "Premium Seller", role: "OCS", receiver: "Super Admin Manager", receiverRole: "SAM", date: "2026-07-02", time: "18:00", country: "Qatar", department: "Revenue Distribution", status: "review", statusId: "review", description: "Weekly sales summary June 27 - July 3", comments: "Under review by SAM team", attachments: 5 },
    { id: "RPT-2845", type: "Customer Payment Report", sender: "Premium Seller", role: "OCS", receiver: "Super Admin Manager", receiverRole: "SAM", date: "2026-07-02", time: "10:15", country: "Qatar", department: "Revenue Distribution", status: "submitted", statusId: "submitted", description: "Customer payment verification records", comments: "", attachments: 4 },
    { id: "RPT-2844", type: "Monthly Sales Report", sender: "Premium Seller", role: "OCS", receiver: "Super Admin Manager", receiverRole: "SAM", date: "2026-07-01", time: "09:00", country: "Qatar", department: "Revenue Distribution", status: "draft", statusId: "draft", description: "June 2026 monthly sales summary - draft", comments: "Pending final figures", attachments: 2 },
    { id: "RPT-2843", type: "Fraud Report", sender: "Premium Seller", role: "OCS", receiver: "Super Admin Manager", receiverRole: "SAM", date: "2026-06-30", time: "22:30", country: "Qatar", department: "Revenue Distribution", status: "completed", statusId: "completed", description: "Suspicious transaction flagged and reported", comments: "Investigation completed, account suspended", attachments: 6 },
    { id: "RPT-2842", type: "Coin Distribution Report", sender: "Premium Seller", role: "OCS", receiver: "Super Admin Manager", receiverRole: "SAM", date: "2026-06-29", time: "16:45", country: "Qatar", department: "Revenue Distribution", status: "rejected", statusId: "rejected", description: "Coin distribution logs for June 29", comments: "Missing receipt attachments", attachments: 1 },
    { id: "RPT-2841", type: "Pending Payment Report", sender: "Premium Seller", role: "OCS", receiver: "Super Admin Manager", receiverRole: "SAM", date: "2026-06-28", time: "11:20", country: "Qatar", department: "Revenue Distribution", status: "returned", statusId: "returned", description: "Pending payments awaiting customer confirmation", comments: "Please add customer contact details", attachments: 3 },
    { id: "RPT-2840", type: "Sales Performance Report", sender: "Premium Seller", role: "OCS", receiver: "Super Admin Manager", receiverRole: "SAM", date: "2026-06-27", time: "20:00", country: "Qatar", department: "Revenue Distribution", status: "approved", statusId: "approved", description: "Q2 sales performance analysis", comments: "Excellent performance, bonus approved", attachments: 8 },
  ],
  approvalHistory: [
    { reportId: "RPT-2847", action: "Created", by: "Premium Seller", role: "OCS", date: "2026-07-03", time: "14:00" },
    { reportId: "RPT-2847", action: "Submitted", by: "Premium Seller", role: "OCS", date: "2026-07-03", time: "14:32" },
    { reportId: "RPT-2847", action: "Under Review", by: "SAM Office", role: "SAM", date: "2026-07-03", time: "15:10" },
    { reportId: "RPT-2847", action: "Approved", by: "Super Admin Manager", role: "SAM", date: "2026-07-03", time: "16:45" },
  ],
  stats: {
    total: 47,
    approved: 28,
    pending: 6,
    rejected: 3,
    drafts: 5,
    completed: 4,
    returned: 1,
  },
};