export const SELLER_DASHBOARD = {
  stats: {
    totalRecharges: 0,
    monthlyRecharge: 0,
    totalCustomers: 0,
    sellerBalance: 0,
    todayRecharges: 0,
    totalEarnings: 0,
    bonusCoins: 0,
    pendingWithdrawals: 0,
  },
  sellerInfo: {
    name: "Premium Seller",
    level: "Gold Seller",
    levelNum: 3,
    badge: "🥇",
    nextLevel: "Diamond Seller",
    monthlyRecharge: 5240,
    monthlyTarget: 10000,
    memberSince: "Jan 2025",
    sellerId: "VYRO-SL-2847",
    commission: "15%",
  },
  packages: [
    { tier: "Starter", color: "#22D3EE", items: [
      { price: 10, coins: 300000, bonus: "Standard" },
      { price: 20, coins: 700000, bonus: "+3%" },
      { price: 30, coins: 1200000, bonus: "+5%" },
      { price: 50, coins: 2200000, bonus: "+7%" },
      { price: 100, coins: 5000000, bonus: "+10%" },
    ]},
    { tier: "Medium", color: "#F59E0B", items: [
      { price: 200, coins: 12000000, bonus: "+12%" },
      { price: 300, coins: 19000000, bonus: "+13%" },
      { price: 500, coins: 35000000, bonus: "+15%" },
      { price: 700, coins: 52000000, bonus: "+17%" },
      { price: 1000, coins: 80000000, bonus: "+20%" },
    ]},
    { tier: "VIP Seller", color: "#A855F7", items: [
      { price: 1500, coins: 130000000, bonus: "+22%" },
      { price: 2000, coins: 185000000, bonus: "+25%" },
      { price: 2500, coins: 240000000, bonus: "+28%" },
      { price: 3000, coins: 310000000, bonus: "+30%" },
      { price: 4000, coins: 430000000, bonus: "+33%" },
      { price: 5000, coins: 560000000, bonus: "+35%" },
    ]},
  ],
  sellerLevels: [
    { id: 1, name: "Bronze Seller", icon: "🥉", color: "#CD7F32", requirement: "$500 monthly", reqNum: 500, benefits: ["Extra 5% coins", "Bronze seller badge", "Faster recharge support"] },
    { id: 2, name: "Silver Seller", icon: "🥈", color: "#C0C0C0", requirement: "$2,000 monthly", reqNum: 2000, benefits: ["Extra 10% coins", "Silver seller badge", "Priority support", "Early events access"] },
    { id: 3, name: "Gold Seller", icon: "🥇", color: "#FFD700", requirement: "$5,000 monthly", reqNum: 5000, benefits: ["Extra 15% coins", "Gold seller badge", "VIP recharge support", "Special promotions"] },
    { id: 4, name: "Diamond Seller", icon: "💎", color: "#B9F2FF", requirement: "$10,000 monthly", reqNum: 10000, benefits: ["Extra 20% coins", "Diamond seller badge", "Dedicated manager", "Premium rewards", "Highest recharge priority"] },
  ],
  benefits: [
    { icon: "💰", title: "Cheaper Coins", desc: "Offline coins cheaper than online store" },
    { icon: "🎁", title: "Bigger Bonuses", desc: "Extra bonus coins on every package" },
    { icon: "👑", title: "VIP Benefits", desc: "VIP recharge benefits & perks" },
    { icon: "⚡", title: "Fast Bulk Recharge", desc: "Instant bulk coin delivery" },
    { icon: "🌟", title: "Seller Promotions", desc: "Extra seller-only promotions" },
    { icon: "🎉", title: "Special Offers", desc: "Exclusive recharge offers" },
    { icon: "🛡️", title: "Priority Support", desc: "Priority recharge support 24/7" },
  ],
  rechargeHistory: [
    { id: "RC-2847", customer: "Alex Kumar", userId: "VYRO-1029", amount: 100, coins: 5500000, status: "completed", date: "2026-07-03", time: "14:32" },
    { id: "RC-2846", customer: "Sarah Lee", userId: "VYRO-1038", amount: 50, coins: 2354000, status: "completed", date: "2026-07-03", time: "12:15" },
    { id: "RC-2845", customer: "Mike Chen", userId: "VYRO-1052", amount: 500, coins: 40250000, status: "completed", date: "2026-07-02", time: "20:48" },
    { id: "RC-2844", customer: "Emma Wilson", userId: "VYRO-1077", amount: 200, coins: 13440000, status: "completed", date: "2026-07-02", time: "16:22" },
    { id: "RC-2843", customer: "John Davis", userId: "VYRO-1091", amount: 30, coins: 1260000, status: "pending", date: "2026-07-03", time: "09:05" },
    { id: "RC-2842", customer: "Lisa Brown", userId: "VYRO-1103", amount: 1000, coins: 96000000, status: "completed", date: "2026-07-01", time: "22:10" },
  ],
  customers: [
    { id: "VYRO-1029", name: "Alex Kumar", avatar: "AK", totalRecharges: 15, totalSpent: 1500, isVip: true, isFavorite: true, lastRecharge: "2026-07-03", status: "active", color: "#3B82F6" },
    { id: "VYRO-1038", name: "Sarah Lee", avatar: "SL", totalRecharges: 8, totalSpent: 400, isVip: false, isFavorite: true, lastRecharge: "2026-07-03", status: "active", color: "#EC4899" },
    { id: "VYRO-1052", name: "Mike Chen", avatar: "MC", totalRecharges: 22, totalSpent: 5200, isVip: true, isFavorite: false, lastRecharge: "2026-07-02", status: "active", color: "#F59E0B" },
    { id: "VYRO-1077", name: "Emma Wilson", avatar: "EW", totalRecharges: 5, totalSpent: 600, isVip: false, isFavorite: false, lastRecharge: "2026-07-02", status: "active", color: "#10B981" },
    { id: "VYRO-1091", name: "John Davis", avatar: "JD", totalRecharges: 3, totalSpent: 90, isVip: false, isFavorite: false, lastRecharge: "2026-07-03", status: "pending", color: "#6366F1" },
    { id: "VYRO-1103", name: "Lisa Brown", avatar: "LB", totalRecharges: 12, totalSpent: 3000, isVip: true, isFavorite: true, lastRecharge: "2026-07-01", status: "active", color: "#A855F7" },
  ],
  rankings: [
    { rank: 1, name: "ProSeller Global", avatar: "PS", total: 45000, recharges: 128, change: "up", color: "#FFD700" },
    { rank: 2, name: "EliteCoins Hub", avatar: "EC", total: 38000, recharges: 95, change: "up", color: "#C0C0C0" },
    { rank: 3, name: "Premium Seller", avatar: "PS", total: 32000, recharges: 87, change: "same", color: "#CD7F32" },
    { rank: 4, name: "MegaRecharge Co", avatar: "MR", total: 28000, recharges: 72, change: "down", color: "#22D3EE" },
    { rank: 5, name: "FastCoins Pro", avatar: "FC", total: 22000, recharges: 61, change: "up", color: "#A855F7" },
  ],
  rewards: [
    { icon: "🎁", title: "Monthly Bonus", desc: "Earn up to $500 monthly bonus", color: "#F59E0B" },
    { icon: "🏆", title: "Event Rewards", desc: "Special rewards during events", color: "#22D3EE" },
    { icon: "🌟", title: "Seasonal Promotions", desc: "Exclusive seasonal seller promos", color: "#A855F7" },
    { icon: "👑", title: "VIP Seller Gifts", desc: "Premium gifts for top sellers", color: "#FFD700" },
    { icon: "📊", title: "Top Seller Rankings", desc: "Compete for #1 seller spot", color: "#3B82F6" },
    { icon: "💎", title: "Performance Rewards", desc: "Rewards based on performance", color: "#10B981" },
  ],
  security: [
    { icon: "✅", title: "Seller Verification", desc: "KYC verified seller account", status: "verified" },
    { icon: "🔐", title: "OTP Verification", desc: "2FA enabled on all transactions", status: "active" },
    { icon: "🛡️", title: "Fraud Protection", desc: "AI-powered fraud detection active", status: "active" },
    { icon: "📱", title: "Device Verification", desc: "Trusted device registered", status: "verified" },
    { icon: "⚠️", title: "Risk Alerts", desc: "Real-time risk monitoring", status: "active" },
    { icon: "🔍", title: "Suspicious Activity", desc: "Auto-detection enabled", status: "active" },
  ],
  processFlow: [
    { step: 1, title: "User Contacts Seller", icon: "💬", desc: "Customer reaches out to purchase coins" },
    { step: 2, title: "Payment Completed", icon: "💳", desc: "Customer pays the seller directly" },
    { step: 3, title: "Seller Sends Coins", icon: "📤", desc: "Seller manually sends coins to user ID" },
    { step: 4, title: "User Receives Notification", icon: "🔔", desc: "Instant recharge notification sent" },
    { step: 5, title: "History Updated", icon: "✅", desc: "Recharge history auto-updated" },
  ],
  notifications: [
    { type: "success", icon: "✅", title: "Recharge Successful", desc: "5,500,000 coins sent to Alex Kumar", time: "2m ago" },
    { type: "warning", icon: "⏳", title: "Recharge Pending", desc: "John Davis recharge awaiting confirmation", time: "15m ago" },
    { type: "reward", icon: "🎁", title: "Monthly Bonus", desc: "You earned $250 monthly bonus!", time: "1h ago" },
    { type: "alert", icon: "⚠️", title: "Fraud Warning", desc: "Suspicious login attempt blocked", time: "3h ago" },
    { type: "vip", icon: "👑", title: "VIP Seller Alert", desc: "You qualified for VIP seller rewards", time: "5h ago" },
  ],
  tabs: [
    { id: "overview", label: "Overview", icon: "📊" },
    { id: "recharge", label: "Recharge", icon: "⚡" },
    { id: "packages", label: "Packages", icon: "📦" },
    { id: "customers", label: "Customers", icon: "👥" },
    { id: "levels", label: "Levels", icon: "🏆" },
    { id: "rewards", label: "Rewards", icon: "🎁" },
    { id: "rankings", label: "Rankings", icon: "🏅" },
    { id: "security", label: "Security", icon: "🛡️" },
    { id: "policy", label: "Policy", icon: "📜" },
    { id: "reports", label: "Reports", icon: "📤" },
  ],
};