export const FINANCE_COLORS = {
  navy: "#0F1B3D",
  navyLight: "#1A2952",
  navyGradient: "linear-gradient(135deg, #0F1B3D 0%, #1A2952 100%)",
  emerald: "#10B981",
  emeraldDark: "#059669",
  royalBlue: "#2563EB",
  royalBlueDark: "#1D4ED8",
  gold: "#D4AF37",
  goldLight: "#E5C158",
  success: "#22C55E",
  warning: "#F59E0B",
  error: "#EF4444",
  info: "#3B82F6",
  bg: "#F5F7FA",
  card: "#FFFFFF",
  textPrimary: "#0F1B3D",
  textSecondary: "#6B7280",
  border: "#E5E7EB",
};

export const FINANCE_CATEGORIES = [
  {
    id: "dashboard",
    title: "Finance Dashboard",
    icon: "📊",
    color: "emerald",
    gradient: "linear-gradient(135deg, #059669, #10B981)",
    options: [
      { name: "Finance Dashboard", icon: "📊" },
      { name: "Financial Overview", icon: "📋" },
      { name: "Revenue Summary", icon: "💰" },
      { name: "Expense Summary", icon: "📉" },
      { name: "Net Revenue", icon: "🪙" },
      { name: "Financial Analytics", icon: "📈" },
      { name: "Financial Reports", icon: "📄" },
      { name: "Finance Notifications", icon: "🔔" },
    ],
  },
  {
    id: "recharge",
    title: "Coins Recharge",
    icon: "⚡",
    color: "gold",
    gradient: "linear-gradient(135deg, #B8941E, #D4AF37)",
    options: [
      { name: "Coins Recharge", icon: "⚡" },
      { name: "Recharge Packages", icon: "📦" },
      { name: "Package Details", icon: "📋" },
      { name: "Package Benefits", icon: "🎁" },
      { name: "Bonus Coins", icon: "✨" },
      { name: "Coins Purchase History", icon: "📜" },
      { name: "Payment History", icon: "💳" },
      { name: "Payment Status", icon: "✅" },
      { name: "Payment Receipt", icon: "🧾" },
    ],
  },
  {
    id: "wallet",
    title: "Wallet",
    icon: "👛",
    color: "royalBlue",
    gradient: "linear-gradient(135deg, #1D4ED8, #2563EB)",
    options: [
      { name: "Coins Wallet", icon: "👛" },
      { name: "Wallet Balance", icon: "💰" },
      { name: "Available Coins", icon: "🪙" },
      { name: "Used Coins", icon: "🔄" },
      { name: "Wallet Transactions", icon: "📋" },
      { name: "Wallet Ledger", icon: "📔" },
    ],
  },
  {
    id: "gifts",
    title: "Gifts & Revenue",
    icon: "🎁",
    color: "gold",
    gradient: "linear-gradient(135deg, #B8941E, #E5C158)",
    options: [
      { name: "Gift Transactions", icon: "🎁" },
      { name: "Gift Revenue", icon: "💎" },
      { name: "Host Earnings", icon: "🎤" },
      { name: "Agency Earnings", icon: "🏢" },
      { name: "Agent Earnings", icon: "👔" },
      { name: "Platform Revenue", icon: "🌐" },
      { name: "Commission Summary", icon: "📊" },
      { name: "Commission Distribution", icon: "📐" },
      { name: "Revenue Breakdown", icon: "🧩" },
    ],
  },
  {
    id: "withdrawals",
    title: "Withdrawals",
    icon: "🏦",
    color: "emerald",
    gradient: "linear-gradient(135deg, #047857, #10B981)",
    options: [
      { name: "Withdraw Dashboard", icon: "🏦" },
      { name: "Withdraw Request", icon: "📝" },
      { name: "Withdraw History", icon: "📜" },
      { name: "Withdraw Status", icon: "📌" },
      { name: "Pending Withdrawals", icon: "⏳" },
      { name: "Approved Withdrawals", icon: "✅" },
      { name: "Rejected Withdrawals", icon: "❌" },
      { name: "Processing Withdrawals", icon: "⚙️" },
      { name: "Withdrawal Details", icon: "🔍" },
      { name: "Withdrawal Receipt", icon: "🧾" },
    ],
  },
  {
    id: "payment",
    title: "Payment Methods",
    icon: "💳",
    color: "royalBlue",
    gradient: "linear-gradient(135deg, #1E40AF, #3B82F6)",
    options: [
      { name: "Payment Methods", icon: "💳" },
      { name: "PayPal Account", icon: "🅿️" },
      { name: "Linked Payment Accounts", icon: "🔗" },
      { name: "Verified Payment Methods", icon: "✅" },
      { name: "Primary Payment Method", icon: "⭐" },
    ],
  },
  {
    id: "kyc",
    title: "KYC & Verification",
    icon: "🪪",
    color: "emerald",
    gradient: "linear-gradient(135deg, #065F46, #10B981)",
    options: [
      { name: "KYC Verification", icon: "🪪" },
      { name: "Identity Verification", icon: "🆔" },
      { name: "Selfie Verification", icon: "🤳" },
      { name: "Document Verification", icon: "📄" },
      { name: "Phone Verification", icon: "📱" },
      { name: "Email Verification", icon: "📧" },
      { name: "Verification Status", icon: "✅" },
    ],
  },
  {
    id: "payout",
    title: "Payout Management",
    icon: "💸",
    color: "gold",
    gradient: "linear-gradient(135deg, #92400E, #D4AF37)",
    options: [
      { name: "Payout Dashboard", icon: "💸" },
      { name: "PayPal Payout", icon: "🅿️" },
      { name: "Payout Queue", icon: "📋" },
      { name: "Payout History", icon: "📜" },
      { name: "Payout Status", icon: "📊" },
      { name: "Payout Logs", icon: "🗂️" },
      { name: "Transaction Reference", icon: "🔢" },
    ],
  },
  {
    id: "admin",
    title: "Finance Administration",
    icon: "🗂️",
    color: "royalBlue",
    gradient: "linear-gradient(135deg, #1E3A8A, #2563EB)",
    options: [
      { name: "Finance Manager Dashboard", icon: "👔" },
      { name: "Finance Reports", icon: "📄" },
      { name: "Financial Statistics", icon: "📊" },
      { name: "Revenue Analytics", icon: "📈" },
      { name: "Country Revenue", icon: "🌍" },
      { name: "Agency Revenue", icon: "🏢" },
      { name: "Agent Revenue", icon: "💼" },
      { name: "Host Revenue", icon: "🎤" },
      { name: "Platform Earnings", icon: "🌐" },
    ],
  },
  {
    id: "notifications",
    title: "Notifications",
    icon: "🔔",
    color: "gold",
    gradient: "linear-gradient(135deg, #B45309, #F59E0B)",
    options: [
      { name: "Recharge Notifications", icon: "⚡" },
      { name: "Payment Notifications", icon: "💳" },
      { name: "Withdrawal Notifications", icon: "🏦" },
      { name: "Payout Notifications", icon: "💸" },
      { name: "Finance Alerts", icon: "⚠️" },
      { name: "Financial Activity Log", icon: "📋" },
    ],
  },
  {
    id: "settings",
    title: "Settings",
    icon: "⚙️",
    color: "emerald",
    gradient: "linear-gradient(135deg, #064E3B, #10B981)",
    options: [
      { name: "Finance Settings", icon: "⚙️" },
      { name: "Payment Gateway Settings", icon: "🔌" },
      { name: "Recharge Package Settings", icon: "📦" },
      { name: "Withdrawal Settings", icon: "🏦" },
      { name: "Commission Settings", icon: "📊" },
      { name: "Payout Settings", icon: "💸" },
      { name: "Currency Settings", icon: "💱" },
      { name: "Financial System Configuration", icon: "🎛️" },
    ],
  },
];

export const FINANCE_QUICK_STATS = [
  { label: "Total Revenue", value: "$2.8M", icon: "💰", color: "emerald" },
  { label: "Wallet Balance", value: "$845K", icon: "👛", color: "royalBlue" },
  { label: "Withdrawals", value: "23", icon: "🏦", color: "gold" },
  { label: "Transactions", value: "1,290", icon: "💳", color: "info" },
];