export const FINANCE_COLORS = {
  navy: "#0F1B3D",
  navyLight: "#1A2952",
  navyGradient: "linear-gradient(135deg, #0F1B3D 0%, #1A2952 100%)",
  emerald: "#10B981",
  emeraldDark: "#059669",
  royalBlue: "#2563EB",
  royalBlueDark: "#1D4ED8",
  gold: "#D4AF37",
  goldLight: "#E5C158",
  success: "#22C55E",
  warning: "#F59E0B",
  error: "#EF4444",
  info: "#3B82F6",
  bg: "#F5F7FA",
  card: "#FFFFFF",
  textPrimary: "#0F1B3D",
  textSecondary: "#6B7280",
  border: "#E5E7EB",
};

export const FINANCE_CATEGORIES = [
  {
    id: "dashboard",
    title: "Finance Dashboard",
    icon: "📊",
    color: "emerald",
    gradient: "linear-gradient(135deg, #059669, #10B981)",
    options: [
      { name: "Finance Dashboard", icon: "📊", route: "/finance-manager/dashboard" },
      { name: "Financial Overview", icon: "📋", route: "/finance-manager/dashboard" },
      { name: "Revenue Summary", icon: "💰", route: "/finance-manager/revenue" },
      { name: "Expense Summary", icon: "📉", route: "/finance-manager/profit-loss" },
      { name: "Net Revenue", icon: "🪙", route: "/finance-manager/profit-loss" },
      { name: "Financial Analytics", icon: "📈", route: "/finance-manager/analytics" },
      { name: "Financial Reports", icon: "📄", route: "/finance-manager/reports" },
      { name: "Finance Notifications", icon: "🔔", route: "/finance-manager/communication" },
    ],
  },
  {
    id: "recharge",
    title: "Coins Recharge",
    icon: "⚡",
    color: "gold",
    gradient: "linear-gradient(135deg, #B8941E, #D4AF37)",
    options: [
      { name: "Coins Recharge", icon: "⚡", route: "/coins-recharge" },
      { name: "Recharge Packages", icon: "📦", route: "/finance-manager/coins" },
      { name: "Package Details", icon: "📋", route: "/finance-manager/coins" },
      { name: "Package Benefits", icon: "🎁", route: "/finance-manager/coins" },
      { name: "Bonus Coins", icon: "✨", route: "/finance-manager/coins" },
      { name: "Coins Purchase History", icon: "📜", route: "/finance-manager/coins" },
      { name: "Payment History", icon: "💳", route: "/finance-manager/payments" },
      { name: "Payment Status", icon: "✅", route: "/finance-manager/payments" },
      { name: "Payment Receipt", icon: "🧾", route: "/finance-manager/payments" },
    ],
  },
  {
    id: "wallet",
    title: "Wallet",
    icon: "👛",
    color: "royalBlue",
    gradient: "linear-gradient(135deg, #1D4ED8, #2563EB)",
    options: [
      { name: "Coins Wallet", icon: "👛", route: "/finance-manager/wallets" },
      { name: "Wallet Balance", icon: "💰", route: "/finance-manager/wallets" },
      { name: "Available Coins", icon: "🪙", route: "/finance-manager/wallets" },
      { name: "Used Coins", icon: "🔄", route: "/finance-manager/wallets" },
      { name: "Wallet Transactions", icon: "📋", route: "/finance-manager/wallets" },
      { name: "Wallet Ledger", icon: "📔", route: "/finance-manager/wallets" },
    ],
  },
  {
    id: "gifts",
    title: "Gifts & Revenue",
    icon: "🎁",
    color: "gold",
    gradient: "linear-gradient(135deg, #B8941E, #E5C158)",
    options: [
      { name: "Gift Transactions", icon: "🎁", route: "/finance-manager/gifts" },
      { name: "Gift Revenue", icon: "💎", route: "/finance-manager/gifts" },
      { name: "Host Earnings", icon: "🎤", route: "/finance-manager/top-earners" },
      { name: "Agency Earnings", icon: "🏢", route: "/finance-manager/top-earners" },
      { name: "Agent Earnings", icon: "👔", route: "/finance-manager/top-earners" },
      { name: "Platform Revenue", icon: "🌐", route: "/finance-manager/revenue" },
      { name: "Commission Summary", icon: "📊", route: "/finance-manager/commissions" },
      { name: "Commission Distribution", icon: "📐", route: "/finance-manager/commissions" },
      { name: "Revenue Breakdown", icon: "🧩", route: "/finance-manager/revenue" },
    ],
  },
  {
    id: "withdrawals",
    title: "Withdrawals",
    icon: "🏦",
    color: "emerald",
    gradient: "linear-gradient(135deg, #047857, #10B981)",
    options: [
      { name: "Withdraw Dashboard", icon: "🏦", route: "/finance-manager/withdrawals" },
      { name: "Withdraw Request", icon: "📝", route: "/finance-manager/withdrawals" },
      { name: "Withdraw History", icon: "📜", route: "/finance-manager/withdrawals" },
      { name: "Withdraw Status", icon: "📌", route: "/finance-manager/withdrawals" },
      { name: "Pending Withdrawals", icon: "⏳", route: "/finance-manager/withdrawals" },
      { name: "Approved Withdrawals", icon: "✅", route: "/finance-manager/withdrawals" },
      { name: "Rejected Withdrawals", icon: "❌", route: "/finance-manager/withdrawals" },
      { name: "Processing Withdrawals", icon: "⚙️", route: "/finance-manager/withdrawals" },
      { name: "Withdrawal Details", icon: "🔍", route: "/finance-manager/withdrawals" },
      { name: "Withdrawal Receipt", icon: "🧾", route: "/finance-manager/withdrawals" },
    ],
  },
  {
    id: "payment",
    title: "Payment Methods",
    icon: "💳",
    color: "royalBlue",
    gradient: "linear-gradient(135deg, #1E40AF, #3B82F6)",
    options: [
      { name: "Payment Methods", icon: "💳", route: "/finance-manager/payments" },
      { name: "PayPal Account", icon: "🅿️", route: "/finance-manager/payments" },
      { name: "Linked Payment Accounts", icon: "🔗", route: "/finance-manager/payments" },
      { name: "Verified Payment Methods", icon: "✅", route: "/finance-manager/payments" },
      { name: "Primary Payment Method", icon: "⭐", route: "/finance-manager/payments" },
    ],
  },
  {
    id: "kyc",
    title: "KYC & Verification",
    icon: "🪪",
    color: "emerald",
    gradient: "linear-gradient(135deg, #065F46, #10B981)",
    options: [
      { name: "KYC Verification", icon: "🪪", route: "/finance-manager/audit" },
      { name: "Identity Verification", icon: "🆔", route: "/finance-manager/audit" },
      { name: "Selfie Verification", icon: "🤳", route: "/finance-manager/audit" },
      { name: "Document Verification", icon: "📄", route: "/finance-manager/audit" },
      { name: "Phone Verification", icon: "📱", route: "/finance-manager/audit" },
      { name: "Email Verification", icon: "📧", route: "/finance-manager/audit" },
      { name: "Verification Status", icon: "✅", route: "/finance-manager/audit" },
    ],
  },
  {
    id: "payout",
    title: "Payout Management",
    icon: "💸",
    color: "gold",
    gradient: "linear-gradient(135deg, #92400E, #D4AF37)",
    options: [
      { name: "Payout Dashboard", icon: "💸", route: "/finance-manager/withdrawals" },
      { name: "PayPal Payout", icon: "🅿️", route: "/finance-manager/withdrawals" },
      { name: "Payout Queue", icon: "📋", route: "/finance-manager/withdrawals" },
      { name: "Payout History", icon: "📜", route: "/finance-manager/withdrawals" },
      { name: "Payout Status", icon: "📊", route: "/finance-manager/withdrawals" },
      { name: "Payout Logs", icon: "🗂️", route: "/finance-manager/withdrawals" },
      { name: "Transaction Reference", icon: "🔢", route: "/finance-manager/withdrawals" },
    ],
  },
  {
    id: "admin",
    title: "Finance Administration",
    icon: "🗂️",
    color: "royalBlue",
    gradient: "linear-gradient(135deg, #1E3A8A, #2563EB)",
    options: [
      { name: "Finance Manager Dashboard", icon: "👔", route: "/finance-manager/dashboard" },
      { name: "Finance Reports", icon: "📄", route: "/finance-manager/reports" },
      { name: "Financial Statistics", icon: "📊", route: "/finance-manager/analytics" },
      { name: "Revenue Analytics", icon: "📈", route: "/finance-manager/analytics" },
      { name: "Country Revenue", icon: "🌍", route: "/finance-manager/countries" },
      { name: "Agency Revenue", icon: "🏢", route: "/finance-manager/top-earners" },
      { name: "Agent Revenue", icon: "💼", route: "/finance-manager/top-earners" },
      { name: "Host Revenue", icon: "🎤", route: "/finance-manager/top-earners" },
      { name: "Platform Earnings", icon: "🌐", route: "/finance-manager/revenue" },
    ],
  },
  {
    id: "notifications",
    title: "Notifications",
    icon: "🔔",
    color: "gold",
    gradient: "linear-gradient(135deg, #B45309, #F59E0B)",
    options: [
      { name: "Recharge Notifications", icon: "⚡", route: "/finance-manager/communication" },
      { name: "Payment Notifications", icon: "💳", route: "/finance-manager/communication" },
      { name: "Withdrawal Notifications", icon: "🏦", route: "/finance-manager/communication" },
      { name: "Payout Notifications", icon: "💸", route: "/finance-manager/communication" },
      { name: "Finance Alerts", icon: "⚠️", route: "/finance-manager/communication" },
      { name: "Financial Activity Log", icon: "📋", route: "/finance-manager/communication" },
    ],
  },
  {
    id: "settings",
    title: "Settings",
    icon: "⚙️",
    color: "emerald",
    gradient: "linear-gradient(135deg, #064E3B, #10B981)",
    options: [
      { name: "Finance Settings", icon: "⚙️", route: "/finance-manager/settings" },
      { name: "Payment Gateway Settings", icon: "🔌", route: "/finance-manager/settings" },
      { name: "Recharge Package Settings", icon: "📦", route: "/finance-manager/settings" },
      { name: "Withdrawal Settings", icon: "🏦", route: "/finance-manager/settings" },
      { name: "Commission Settings", icon: "📊", route: "/finance-manager/settings" },
      { name: "Payout Settings", icon: "💸", route: "/finance-manager/settings" },
      { name: "Currency Settings", icon: "💱", route: "/finance-manager/settings" },
      { name: "Financial System Configuration", icon: "🎛️", route: "/finance-manager/settings" },
    ],
  },
];

export const FINANCE_QUICK_STATS = [
  { label: "Total Revenue", value: "$2.8M", icon: "💰", color: "emerald" },
  { label: "Wallet Balance", value: "$845K", icon: "👛", color: "royalBlue" },
  { label: "Withdrawals", value: "23", icon: "🏦", color: "gold" },
  { label: "Transactions", value: "1,290", icon: "💳", color: "info" },
];