export const RECHARGE_TIERS = [
  {
    id: "starter_1",
    tier: 1,
    group: "starter",
    label: "STARTER",
    price: 1,
    color: "#22C55E",
    gradient: "linear-gradient(135deg, #16A34A, #22C55E)",
    coins: 20000,
    bonusPercent: 5,
    bonusCoins: 1000,
    totalCoins: 21000,
    benefitsDuration: "24 Hours",
    benefits: [
      "Basic Profile Frame (24h)",
      "Entry Light Effect (24h)",
      "Chat Color Unlock (24h)",
      "Basic VIP Badge (24h)",
      "Room Entry Priority (Low)",
    ],
  },
  {
    id: "starter_2",
    tier: 2,
    group: "starter",
    label: "STARTER",
    price: 2,
    color: "#3B82F6",
    gradient: "linear-gradient(135deg, #2563EB, #3B82F6)",
    coins: 40000,
    bonusPercent: 7,
    bonusCoins: 2800,
    totalCoins: 42800,
    benefitsDuration: "48 Hours",
    benefits: [
      "Animated Frame (48h)",
      "Chat Bubble Style (48h)",
      "Entry Effect Upgrade (48h)",
      "VIP Name Color (48h)",
      "Medium Room Priority",
    ],
  },
  {
    id: "starter_3",
    tier: 3,
    group: "starter",
    label: "STARTER",
    price: 3,
    color: "#8B5CF6",
    gradient: "linear-gradient(135deg, #7C3AED, #8B5CF6)",
    coins: 60000,
    bonusPercent: 10,
    bonusCoins: 6000,
    totalCoins: 66000,
    benefitsDuration: "2 Days",
    benefits: [
      "Premium Animated Frame (2 days)",
      "Entry Explosion Effect (2 days)",
      "VIP Chat Bubble (2 days)",
      "Emoji Pack Unlock (2 days)",
      "Higher Room Priority",
    ],
  },
  {
    id: "starter_4",
    tier: 4,
    group: "starter",
    label: "STARTER",
    price: 4,
    color: "#EAB308",
    gradient: "linear-gradient(135deg, #CA8A04, #EAB308)",
    coins: 80000,
    bonusPercent: 12,
    bonusCoins: 9600,
    totalCoins: 89600,
    benefitsDuration: "5 Days",
    benefits: [
      "Elite Frame (5 days)",
      "Vehicle Entry Effect (5 days)",
      "VIP Crown Light Effect (5 days)",
      "Profile Highlight Boost (5 days)",
      "High Room Priority",
    ],
  },
  {
    id: "starter_5",
    tier: 5,
    group: "starter",
    label: "STARTER",
    price: 5,
    color: "#EF4444",
    gradient: "linear-gradient(135deg, #DC2626, #EF4444)",
    coins: 100000,
    bonusPercent: 15,
    bonusCoins: 15000,
    totalCoins: 115000,
    benefitsDuration: "5 Days",
    benefits: [
      "Premium Animated Frame (5 days)",
      "Special Entrance Animation (5 days)",
      "VIP Chat Bubble Pro (5 days)",
      "Exclusive Emoji Set (5 days)",
      "Highest Entry Priority (low tier system)",
      "Profile Glow Effect (5 days)",
    ],
  },
  {
    id: "premium_5",
    tier: 6,
    group: "premium",
    label: "BRONZE",
    price: 5,
    color: "#22C55E",
    gradient: "linear-gradient(135deg, #15803D, #22C55E)",
    coins: 100000,
    bonusPercent: 5,
    bonusCoins: 5000,
    totalCoins: 105000,
    benefitsDuration: "5 Days",
    benefits: [
      "Basic Animated Frame",
      "Entry Light Effect",
      "Chat Color Unlock",
      "VIP Badge (Temporary)",
      "Room Entry Priority (Low)",
    ],
  },
  {
    id: "premium_10",
    tier: 7,
    group: "premium",
    label: "SILVER",
    price: 10,
    color: "#3B82F6",
    gradient: "linear-gradient(135deg, #1D4ED8, #3B82F6)",
    coins: 200000,
    bonusPercent: 7,
    bonusCoins: 14000,
    totalCoins: 214000,
    benefitsDuration: "7 Days",
    benefits: [
      "Animated Frame Upgrade",
      "Chat Bubble Style",
      "Entry Effect (Medium)",
      "Profile Highlight",
      "Priority Room Entry",
    ],
  },
  {
    id: "premium_20",
    tier: 8,
    group: "premium",
    label: "SILVER+",
    price: 20,
    color: "#8B5CF6",
    gradient: "linear-gradient(135deg, #6D28D9, #8B5CF6)",
    coins: 400000,
    bonusPercent: 8,
    bonusCoins: 32000,
    totalCoins: 432000,
    benefitsDuration: "7 Days",
    benefits: [
      "Premium Frame",
      "Entrance Explosion Effect",
      "VIP Chat Bubble",
      "Emoji Pack Unlock",
      "Higher Room Priority",
    ],
  },
  {
    id: "premium_50",
    tier: 9,
    group: "premium",
    label: "GOLD",
    price: 50,
    color: "#EAB308",
    gradient: "linear-gradient(135deg, #A16207, #EAB308)",
    coins: 1000000,
    bonusPercent: 10,
    bonusCoins: 100000,
    totalCoins: 1100000,
    benefitsDuration: "10 Days",
    benefits: [
      "Elite Animated Frame",
      "Vehicle Entry Effect",
      "VIP Crown Glow",
      "Profile Boost Highlight",
      "Advanced Room Priority",
    ],
  },
  {
    id: "premium_100",
    tier: 10,
    group: "premium",
    label: "GOLD+",
    price: 100,
    color: "#EF4444",
    gradient: "linear-gradient(135deg, #B91C1C, #EF4444)",
    coins: 2000000,
    bonusPercent: 12,
    bonusCoins: 240000,
    totalCoins: 2240000,
    benefitsDuration: "15 Days",
    benefits: [
      "Premium Crown Frame",
      "Animated Entrance Effect",
      "VIP Chat Bubble Pro",
      "Exclusive Emoji Set",
      "High Room Priority",
    ],
  },
  {
    id: "premium_200",
    tier: 11,
    group: "premium",
    label: "PLATINUM",
    price: 200,
    color: "#F97316",
    gradient: "linear-gradient(135deg, #C2410C, #F97316)",
    coins: 4000000,
    bonusPercent: 13,
    bonusCoins: 520000,
    totalCoins: 4520000,
    benefitsDuration: "20 Days",
    benefits: [
      "Luxury Animated Frame",
      "Vehicle Effect Pro",
      "VIP Room Access Priority",
      "Profile Theme Glow",
      "Special Ranking Boost",
    ],
  },
  {
    id: "premium_500",
    tier: 12,
    group: "premium",
    label: "PLATINUM+",
    price: 500,
    color: "#A16207",
    gradient: "linear-gradient(135deg, #78350F, #B45309)",
    coins: 10000000,
    bonusPercent: 14,
    bonusCoins: 1400000,
    totalCoins: 11400000,
    benefitsDuration: "30 Days",
    benefits: [
      "Ultra Frame Crown",
      "Super Entrance Animation",
      "VIP Elite Chat Bubble",
      "Private Room Access",
      "High Ranking Boost",
    ],
  },
  {
    id: "premium_1000",
    tier: 13,
    group: "premium",
    label: "DIAMOND",
    price: 1000,
    color: "#1F2937",
    gradient: "linear-gradient(135deg, #111827, #1F2937)",
    coins: 20000000,
    bonusPercent: 15,
    bonusCoins: 3000000,
    totalCoins: 23000000,
    benefitsDuration: "45 Days",
    benefits: [
      "Royal Frame System",
      "Custom Entrance Effect",
      "VIP Vehicle Effect",
      "Profile Theme Customization",
      "Priority Verification",
    ],
  },
  {
    id: "premium_2000",
    tier: 14,
    group: "premium",
    label: "DIAMOND+",
    price: 2000,
    color: "#F59E0B",
    gradient: "linear-gradient(135deg, #B45309, #F59E0B)",
    coins: 40000000,
    bonusPercent: 16,
    bonusCoins: 6400000,
    totalCoins: 46400000,
    benefitsDuration: "60 Days",
    benefits: [
      "Royal Crown Frame",
      "Custom Chat Style",
      "VIP Event Access",
      "High Priority Rooms",
      "Dedicated Support",
    ],
  },
  {
    id: "premium_3000",
    tier: 15,
    group: "premium",
    label: "ELITE",
    price: 3000,
    color: "#0EA5E9",
    gradient: "linear-gradient(135deg, #0369A1, #0EA5E9)",
    coins: 60000000,
    bonusPercent: 17,
    bonusCoins: 10200000,
    totalCoins: 70200000,
    benefitsDuration: "60 Days",
    benefits: [
      "Elite Royal Frame",
      "Custom Profile Theme",
      "Exclusive Entrance Effects",
      "VIP Leaderboard Boost",
      "Premium Event Access",
    ],
  },
  {
    id: "premium_3500",
    tier: 16,
    group: "premium",
    label: "ELITE+",
    price: 3500,
    color: "#0EA5E9",
    gradient: "linear-gradient(135deg, #0E7490, #06B6D4)",
    coins: 70000000,
    bonusPercent: 18,
    bonusCoins: 12600000,
    totalCoins: 82600000,
    benefitsDuration: "75 Days",
    benefits: [
      "Legendary Frame System",
      "Personal VIP Badge Style",
      "Special Room Access",
      "Custom Effects Unlock",
      "Priority Ranking System",
    ],
  },
  {
    id: "premium_4000",
    tier: 17,
    group: "premium",
    label: "MYTHIC",
    price: 4000,
    color: "#F59E0B",
    gradient: "linear-gradient(135deg, #92400E, #D97706)",
    coins: 80000000,
    bonusPercent: 19,
    bonusCoins: 15200000,
    totalCoins: 95200000,
    benefitsDuration: "90 Days",
    benefits: [
      "Mythic Frame System",
      "Royal Entrance Effects",
      "VIP Private Rooms",
      "Custom Profile Theme",
      "Event Priority Access",
    ],
  },
  {
    id: "premium_4500",
    tier: 18,
    group: "premium",
    label: "MYTHIC+",
    price: 4500,
    color: "#DC2626",
    gradient: "linear-gradient(135deg, #991B1B, #DC2626)",
    coins: 90000000,
    bonusPercent: 20,
    bonusCoins: 18000000,
    totalCoins: 108000000,
    benefitsDuration: "90 Days",
    benefits: [
      "Ultra Royal Frame",
      "Exclusive Identity Badge",
      "Highest Room Priority",
      "VIP Global Ranking Boost",
      "Personal Account Manager",
    ],
  },
  {
    id: "premium_5000",
    tier: 19,
    group: "premium",
    label: "ROYAL KING",
    price: 5000,
    color: "#D4AF37",
    gradient: "linear-gradient(135deg, #B8941E, #D4AF37)",
    coins: 100000000,
    bonusPercent: 22,
    bonusCoins: 22000000,
    totalCoins: 122000000,
    benefitsDuration: "LIFETIME",
    benefits: [
      "Royal King Frame (Animated)",
      "Custom Profile Full Theme",
      "VIP Permanent Badge Style",
      "Highest Priority Everywhere",
      "Private VIP Events Access",
      "Dedicated Manager Support",
      "Early Feature Access",
      "Global Ranking Crown",
    ],
  },
];

export const PAYMENT_METHODS = [
  { id: "paypal", name: "PayPal", icon: "🅿️", color: "#00457C" },
  { id: "visa", name: "Visa Card", icon: "💳", color: "#1A1F71" },
  { id: "mastercard", name: "Mastercard", icon: "💳", color: "#EB001B" },
  { id: "applepay", name: "Apple Pay", icon: "🍎", color: "#000000" },
  { id: "googlepay", name: "Google Pay", icon: "🔷", color: "#4285F4" },
  { id: "crypto", name: "Crypto", icon: "₿", color: "#F7931A" },
];

export const WALLET_INFO = {
  currentBalance: 245000,
  totalRecharged: 1250000,
  totalSpent: 1005000,
  totalBonus: 58000,
  transactions: [
    { id: 1, type: "recharge", amount: 115000, price: 5, date: "2026-06-28", status: "completed", tier: "Starter Tier 5" },
    { id: 2, type: "spend", amount: 5000, date: "2026-06-27", status: "completed", desc: "Gift sent to Host" },
    { id: 3, type: "recharge", amount: 432000, price: 20, date: "2026-06-20", status: "completed", tier: "Premium $20" },
    { id: 4, type: "bonus", amount: 32000, date: "2026-06-20", status: "completed", desc: "Recharge Bonus" },
    { id: 5, type: "spend", amount: 10000, date: "2026-06-15", status: "completed", desc: "VIP Room Entry" },
    { id: 6, type: "recharge", amount: 214000, price: 10, date: "2026-06-10", status: "completed", tier: "Premium $10" },
  ],
};