export const ROLE_HIERARCHY = {
  "owner": {
    title: "Application Owner (AO)",
    icon: "👑",
    reportsTo: "None (Highest Authority)",
    reportsToNote: "Founder & Chief Executive Authority — no reporting manager above this role.",
    positionLevel: "Founder & Chief Executive Authority",
    responsibilities: [
      "Owns the entire VYRO Live Connect platform.",
      "Defines the company's vision, mission, and long-term strategy.",
      "Holds final authority over all business, financial, legal, technical, and operational decisions.",
      "Approves or rejects all executive-level appointments.",
      "Oversees all departments, countries, and global operations.",
      "Controls company assets, intellectual property, and platform ownership.",
      "Approves company policies, regulations, and strategic initiatives.",
    ],
    authority: [
      "Full platform access.",
      "Full financial authority.",
      "Final approval authority.",
      "Final security authority.",
      "Can appoint, suspend, terminate, or remove any role.",
      "Can override any decision made by subordinate roles.",
    ],
    reportsReceivedFrom: ["Super Admin Manager (SAM)", "Country Manager (CM)"],
  },
  "sam": {
    title: "Super Admin Manager (SAM)",
    icon: "👨‍💼",
    reportsTo: "Application Owner (AO)",
    reportsToNote: "Executive Administration Head — reports directly to the Application Owner.",
    positionLevel: "Executive Administration Head",
    responsibilities: [
      "Manage all Super Admin operations.",
      "Supervise administrative departments.",
      "Implement Application Owner directives.",
      "Monitor platform security and administration.",
      "Manage Coin Packages.",
      "Manage VIP Membership Packages.",
      "Manage PK Battle Events.",
      "Approve operational administrative requests.",
      "Supervise platform moderation.",
      "Coordinate with Country Managers.",
    ],
    authority: [
      "Administrative authority delegated by AO.",
      "Can assign or revoke administrative permissions.",
      "Can suspend or recommend dismissal of staff according to company policy.",
      "Can manage system settings delegated by AO.",
    ],
    reportsReceivedFrom: ["Super Admin (SA)", "Offline Coin Seller (OCS)"],
  },
  "country": {
    title: "Country Manager (CM)",
    icon: "🌍",
    reportsTo: "Application Owner (AO)",
    reportsToNote: "National Operations Head — reports directly to the Application Owner.",
    positionLevel: "National Operations Head",
    responsibilities: [
      "Manage all operations within assigned country.",
      "Monitor business performance.",
      "Supervise country departments.",
      "Develop country growth strategy.",
      "Ensure legal and regulatory compliance.",
      "Submit reports to Application Owner.",
    ],
    authority: [
      "Manage all country-level departments.",
      "Approve country operational activities.",
      "Recommend promotions and disciplinary actions.",
    ],
    reportsReceivedFrom: ["Business Developer (BD)"],
  },
  "business-developer": {
    title: "Business Developer (BD)",
    icon: "📈",
    reportsTo: "Country Manager (CM)",
    reportsToNote: "Business Development Executive — reports to the Country Manager.",
    positionLevel: "Business Development Executive",
    responsibilities: [
      "Develop partnerships.",
      "Expand business.",
      "Increase revenue.",
      "Identify new opportunities.",
      "Build agency networks.",
    ],
    authority: [],
    reportsReceivedFrom: ["Business Manager (BM)"],
  },
  "business-manager": {
    title: "Business Manager (BM)",
    icon: "🏢",
    reportsTo: "Business Developer (BD)",
    reportsToNote: "Business Operations Manager — reports to the Business Developer.",
    positionLevel: "Business Operations Manager",
    responsibilities: [
      "Manage daily operations.",
      "Supervise departmental managers.",
      "Monitor KPIs.",
      "Improve operational efficiency.",
      "Coordinate departments.",
    ],
    authority: [],
    reportsReceivedFrom: ["Reward Manager (RM)", "PK Manager (PM)", "Event Manager (EM)", "Support Manager (SM)", "Marketing Manager (MM)", "Finance Manager (FM)"],
  },
  "reward-manager": {
    title: "Reward Manager (RM)",
    icon: "🎁",
    reportsTo: "Business Manager (BM)",
    reportsToNote: "Reports to the Business Manager.",
    positionLevel: "Department Manager — Rewards",
    responsibilities: [
      "Reward programs.",
      "Bonus management.",
      "Incentive distribution.",
      "Reward verification.",
      "Campaign rewards.",
    ],
    authority: [],
    reportsReceivedFrom: [],
  },
  "pk-manager": {
    title: "PK Manager (PM)",
    icon: "⚔️",
    reportsTo: "Business Manager (BM)",
    reportsToNote: "Reports to the Business Manager.",
    positionLevel: "Department Manager — PK Battles",
    responsibilities: [
      "PK Battle management.",
      "PK rankings.",
      "PK scheduling.",
      "Competition monitoring.",
      "PK reward distribution.",
    ],
    authority: [],
    reportsReceivedFrom: [],
  },
  "event-manager": {
    title: "Event Manager (EM)",
    icon: "🎉",
    reportsTo: "Business Manager (BM)",
    reportsToNote: "Reports to the Business Manager.",
    positionLevel: "Department Manager — Events",
    responsibilities: [
      "Plan platform events.",
      "Execute campaigns.",
      "Organize seasonal activities.",
      "Manage live events.",
      "Prepare event reports.",
    ],
    authority: [],
    reportsReceivedFrom: [],
  },
  "support-manager": {
    title: "Support Manager (SM)",
    icon: "🛠️",
    reportsTo: "Business Manager (BM)",
    reportsToNote: "Reports to the Business Manager.",
    positionLevel: "Department Manager — Support",
    responsibilities: [
      "Customer support.",
      "Complaint resolution.",
      "Ticket management.",
      "User satisfaction.",
      "Service quality monitoring.",
    ],
    authority: [],
    reportsReceivedFrom: [],
  },
  "marketing-manager": {
    title: "Marketing Manager (MM)",
    icon: "📢",
    reportsTo: "Business Manager (BM)",
    reportsToNote: "Reports to the Business Manager.",
    positionLevel: "Department Manager — Marketing",
    responsibilities: [
      "Marketing campaigns.",
      "Brand promotion.",
      "User acquisition.",
      "Advertising strategy.",
      "Market research.",
    ],
    authority: [],
    reportsReceivedFrom: [],
  },
  "finance-manager": {
    title: "Finance Manager (FM)",
    icon: "💳",
    reportsTo: "Business Manager (BM)",
    reportsToNote: "Reports to the Business Manager.",
    positionLevel: "Department Manager — Finance",
    responsibilities: [
      "Revenue management.",
      "Financial reporting.",
      "Withdrawal monitoring.",
      "Budget planning.",
      "Payment verification.",
    ],
    authority: [],
    reportsReceivedFrom: [],
  },
  "super-admin": {
    title: "Super Admin (SA)",
    icon: "🧠",
    reportsTo: "Super Admin Manager (SAM)",
    reportsToNote: "Reports to the Super Admin Manager.",
    positionLevel: "Platform Administrator",
    responsibilities: [
      "Platform administration.",
      "User verification.",
      "Security monitoring.",
      "Technical supervision.",
      "Moderation.",
    ],
    authority: [],
    reportsReceivedFrom: ["Admin (AN)"],
  },
  "admin": {
    title: "Admin (AN)",
    icon: "🏢",
    reportsTo: "Super Admin (SA)",
    reportsToNote: "Reports to the Super Admin.",
    positionLevel: "Administrator",
    responsibilities: [
      "User management.",
      "Daily administration.",
      "Account monitoring.",
      "Reports handling.",
      "Operational support.",
    ],
    authority: [],
    reportsReceivedFrom: ["Agent"],
  },
  "agent": {
    title: "Agent",
    icon: "🧑",
    reportsTo: "Admin (AN)",
    reportsToNote: "Reports to the Admin.",
    positionLevel: "Agent",
    responsibilities: [
      "Recruit Hosts.",
      "Manage Hosts.",
      "Community growth.",
      "Performance monitoring.",
      "Team development.",
    ],
    authority: [],
    reportsReceivedFrom: ["Host"],
  },
  "host": {
    title: "Host",
    icon: "🎤",
    reportsTo: "Agent",
    reportsToNote: "Reports to the Agent.",
    positionLevel: "Host",
    responsibilities: [
      "Live streaming.",
      "Audience engagement.",
      "Content creation.",
      "Community interaction.",
      "Gift revenue generation.",
      "Platform policy compliance.",
    ],
    authority: [],
    reportsReceivedFrom: [],
  },
  "seller": {
    title: "Offline Coin Seller (OCS)",
    icon: "🪙",
    reportsTo: "Super Admin Manager (SAM) Only",
    reportsToNote: "Authorized Offline Coin Sales Representative — reports to the Super Admin Manager only.",
    positionLevel: "Authorized Offline Coin Sales Representative",
    responsibilities: [
      "Sell official VYRO Coin Packages through approved offline channels.",
      "Verify customer payment before coin delivery.",
      "Maintain offline sales records.",
      "Submit daily, weekly, and monthly sales reports.",
      "Prevent fraud and unauthorized coin sales.",
      "Follow company pricing and policies.",
      "Keep customer transaction records.",
      "Coordinate with Finance when required.",
      "Maintain confidentiality of customer information.",
    ],
    authority: [],
    reportsReceivedFrom: [],
  },
};