export const mallSections = [
  {
    id: "home",
    name: "Mall Home",
    icon: "🏬",
    gradient: "from-orange-400 to-red-500",
    color: "#F97316",
    subtitle: "Luxury Digital Store",
    description: "Browse featured, new arrivals, trending, limited edition, VIP exclusive, seasonal collections & discount offers.",
    banners: ["Featured Items", "New Arrivals", "Trending Items", "Limited Edition", "VIP Exclusive", "Seasonal Collections", "Discount Offers"],
    actions: ["Buy", "Preview", "Gift", "Add To Collection", "Equip", "Remove"],
    items: [],
  },
  {
    id: "lucky_id",
    name: "Lucky ID",
    icon: "🍀",
    gradient: "from-lime-400 to-green-500",
    color: "#84CC16",
    subtitle: "Golden Lucky Number Card",
    description: "Premium unique ID numbers for users who want special identity.",
    items: [
      { name: "VIP Lucky ID", icon: "🎯", price: "50,000", rarity: "Epic", desc: "Short premium VIP ID with glow effect" },
      { name: "Diamond ID", icon: "💎", price: "200,000", rarity: "Legendary", desc: "Exclusive diamond-studded ID number" },
      { name: "Custom Number ID", icon: "🔢", price: "100,000", rarity: "Epic", desc: "Choose your own special number" },
      { name: "Rare ID Collection", icon: "👑", price: "500,000", rarity: "Mythic", desc: "Ultra-rare collectible ID series" },
    ],
    features: ["Short IDs", "Special Numbers", "Premium Fonts", "Glow Effects", "Animated ID Display"],
    actions: ["Preview ID", "Purchase ID", "Apply ID", "Change ID Style"],
  },
  {
    id: "avatar_frame",
    name: "Avatar Frame",
    icon: "🖼️",
    gradient: "from-purple-400 to-violet-600",
    color: "#A855F7",
    subtitle: "Royal Frame Gallery",
    description: "Premium profile frames around user avatar.",
    items: [
      { name: "VIP Frame", icon: "👑", price: "80,000", rarity: "Epic", desc: "Golden VIP border with shimmer" },
      { name: "Diamond Frame", icon: "💎", price: "300,000", rarity: "Legendary", desc: "Crystal diamond animated border" },
      { name: "Seasonal Frame", icon: "🎄", price: "60,000", rarity: "Rare", desc: "Festive seasonal themed frame" },
      { name: "Event Frame", icon: "🎉", price: "100,000", rarity: "Epic", desc: "Limited event commemorative frame" },
      { name: "Royal Frame", icon: "🏯", price: "400,000", rarity: "Mythic", desc: "Royal palace themed luxury frame" },
      { name: "Animated Frame", icon: "✨", price: "150,000", rarity: "Legendary", desc: "Fully animated premium frame" },
    ],
    features: ["Gold Border", "Crystal Effects", "Fire Animation", "Galaxy Effect"],
    actions: ["Preview", "Equip", "Remove", "Upgrade"],
  },
  {
    id: "entry_effect",
    name: "Entry Effect",
    icon: "🚀",
    gradient: "from-blue-400 to-indigo-600",
    color: "#3B82F6",
    subtitle: "Luxury Entrance Animation",
    description: "Special animation when user enters live rooms.",
    items: [
      { name: "Crown Entry", icon: "👑", price: "120,000", rarity: "Legendary", desc: "Royal crown drop entrance" },
      { name: "Diamond Explosion", icon: "💎", price: "250,000", rarity: "Mythic", desc: "Diamond burst explosion effect" },
      { name: "Fire Entrance", icon: "🔥", price: "90,000", rarity: "Epic", desc: "Flaming fire entry animation" },
      { name: "Dragon Entry", icon: "🐉", price: "350,000", rarity: "Mythic", desc: "Majestic dragon arrival effect" },
      { name: "Galaxy Entrance", icon: "🌌", price: "200,000", rarity: "Legendary", desc: "Cosmic galaxy warp entry" },
      { name: "Royal Car Arrival", icon: "🚗", price: "280,000", rarity: "Mythic", desc: "Luxury royal car entrance" },
    ],
    features: ["3D Animation", "Sound Effects", "Particle Systems"],
    actions: ["Preview Animation", "Activate", "Change Effect", "Set Duration"],
  },
  {
    id: "room_entry",
    name: "Room Entry",
    icon: "🚪",
    gradient: "from-amber-400 to-orange-500",
    color: "#F59E0B",
    subtitle: "VIP Door Effect",
    description: "Special entry identity inside live rooms.",
    items: [
      { name: "Name Highlight", icon: "💡", price: "40,000", rarity: "Rare", desc: "Glowing highlighted username on entry" },
      { name: "Entry Sound", icon: "🔊", price: "70,000", rarity: "Epic", desc: "Custom premium entry sound effect" },
      { name: "Entry Animation", icon: "🎬", price: "110,000", rarity: "Legendary", desc: "Cinematic entry animation sequence" },
      { name: "Special Badge", icon: "🏅", price: "85,000", rarity: "Epic", desc: "Exclusive entry badge display" },
    ],
    features: ["Name Highlight", "Entry Sound", "Animation", "Special Badge"],
    actions: ["Activate", "Disable", "Customize"],
  },
  {
    id: "bubble_chat",
    name: "Bubble Chat",
    icon: "💬",
    gradient: "from-pink-400 to-rose-500",
    color: "#EC4899",
    subtitle: "Magic Chat Bubble",
    description: "Premium chat message styles.",
    items: [
      { name: "Gold Bubble", icon: "🟡", price: "50,000", rarity: "Epic", desc: "Shimmering gold chat bubble" },
      { name: "Diamond Bubble", icon: "💎", price: "180,000", rarity: "Legendary", desc: "Crystal diamond chat bubble" },
      { name: "Fire Bubble", icon: "🔥", price: "80,000", rarity: "Epic", desc: "Animated fire chat bubble" },
      { name: "Neon Bubble", icon: "💡", price: "120,000", rarity: "Legendary", desc: "Glowing neon chat bubble" },
      { name: "Royal Bubble", icon: "👑", price: "200,000", rarity: "Mythic", desc: "Royal themed luxury bubble" },
    ],
    features: ["Animated Messages", "Special Colors", "VIP Effects"],
    actions: ["Apply", "Preview", "Change Style"],
  },
  {
    id: "text_style",
    name: "Text Styles",
    icon: "✍️",
    gradient: "from-cyan-400 to-blue-500",
    color: "#06B6D4",
    subtitle: "Premium Text Editor",
    description: "Special fonts and text effects.",
    items: [
      { name: "Golden Text", icon: "🟨", price: "45,000", rarity: "Epic", desc: "Shimmering golden font style" },
      { name: "Neon Text", icon: "🔆", price: "75,000", rarity: "Epic", desc: "Glowing neon text effect" },
      { name: "Fire Text", icon: "🔥", price: "65,000", rarity: "Epic", desc: "Burning fire text animation" },
      { name: "Diamond Text", icon: "💎", price: "160,000", rarity: "Legendary", desc: "Crystal diamond text style" },
      { name: "Royal Text", icon: "👑", price: "140,000", rarity: "Legendary", desc: "Royal calligraphy text style" },
    ],
    features: ["Premium Fonts", "Color Effects", "Animations"],
    actions: ["Preview", "Apply", "Save Style"],
  },
  {
    id: "room_cover",
    name: "Room Cover",
    icon: "🏠",
    gradient: "from-emerald-400 to-green-500",
    color: "#10B981",
    subtitle: "Live Room Design Studio",
    description: "Premium live room backgrounds and covers.",
    items: [
      { name: "Luxury Room", icon: "🏛️", price: "150,000", rarity: "Legendary", desc: "Luxury palace room theme" },
      { name: "Gaming Room", icon: "🎮", price: "90,000", rarity: "Epic", desc: "Cyber gaming room background" },
      { name: "Music Room", icon: "🎵", price: "80,000", rarity: "Epic", desc: "Studio music room theme" },
      { name: "VIP Room", icon: "💎", price: "220,000", rarity: "Mythic", desc: "Exclusive VIP room design" },
      { name: "Festival Room", icon: "🎉", price: "100,000", rarity: "Epic", desc: "Festive celebration room theme" },
    ],
    features: ["3D Backgrounds", "Animated Covers", "Theme System"],
    actions: ["Preview Room", "Apply Cover", "Change Theme"],
  },
  {
    id: "gifts",
    name: "Gifts",
    icon: "🎁",
    gradient: "from-red-400 to-pink-500",
    color: "#EF4444",
    subtitle: "Luxury Gift Box",
    description: "Virtual gifts with 3D animation and sound effects.",
    items: [
      { name: "Flowers", icon: "💐", price: "1,000", rarity: "Common", desc: "Beautiful flower bouquet gift" },
      { name: "Cars", icon: "🚗", price: "500,000", rarity: "Mythic", desc: "Luxury sports car gift" },
      { name: "Diamonds", icon: "💎", price: "100,000", rarity: "Legendary", desc: "Brilliant diamond gift" },
      { name: "Crowns", icon: "👑", price: "300,000", rarity: "Mythic", desc: "Royal crown gift" },
      { name: "Animals", icon: "🐉", price: "150,000", rarity: "Legendary", desc: "Mythical creature gifts" },
      { name: "Royal Gifts", icon: "🏰", price: "800,000", rarity: "Mythic", desc: "Ultra luxury royal gift" },
      { name: "Legendary Gifts", icon: "⭐", price: "1,000,000", rarity: "Mythic", desc: "Top tier legendary gift" },
    ],
    features: ["3D Animation", "Sound Effects", "Gift Ranking Value"],
    actions: ["Send Gift", "Buy Gift", "Favorite"],
  },
  {
    id: "profile_effects",
    name: "Profile Effects",
    icon: "🌟",
    gradient: "from-violet-400 to-purple-500",
    color: "#8B5CF6",
    subtitle: "Profile Magic Effects",
    description: "Aura, glow, and particle effects for your profile.",
    items: [
      { name: "Aura Effect", icon: "💫", price: "130,000", rarity: "Legendary", desc: "Mystical aura around profile" },
      { name: "Glow Effect", icon: "✨", price: "60,000", rarity: "Epic", desc: "Soft glow around avatar" },
      { name: "Background Animation", icon: "🌊", price: "170,000", rarity: "Legendary", desc: "Animated profile background" },
      { name: "Particle Effect", icon: "🎆", price: "110,000", rarity: "Epic", desc: "Floating particle effects" },
    ],
    features: ["Real-Time Rendering", "Customizable Layers"],
    actions: ["Activate", "Preview", "Change"],
  },
  {
    id: "badges",
    name: "Badges",
    icon: "🏆",
    gradient: "from-yellow-400 to-amber-500",
    color: "#F59E0B",
    subtitle: "Premium Badge Center",
    description: "Collect and equip premium badges.",
    items: [
      { name: "VIP Badge", icon: "💎", price: "90,000", rarity: "Epic", desc: "Exclusive VIP member badge" },
      { name: "Event Badge", icon: "🎊", price: "50,000", rarity: "Rare", desc: "Limited event commemorative badge" },
      { name: "Achievement Badge", icon: "🏅", price: "70,000", rarity: "Epic", desc: "Earned achievement display badge" },
      { name: "Ranking Badge", icon: "🥇", price: "120,000", rarity: "Legendary", desc: "Top ranking position badge" },
      { name: "Founder Badge", icon: "👑", price: "500,000", rarity: "Mythic", desc: "Original founder exclusive badge" },
    ],
    features: ["Multiple Slots", "Animated Badges", " Rarity Display"],
    actions: ["Equip", "Hide", "Replace"],
  },
  {
    id: "voice_effects",
    name: "Voice Effects",
    icon: "🎤",
    gradient: "from-indigo-400 to-blue-500",
    color: "#6366F1",
    subtitle: "Audio Premium Studio",
    description: "Voice frame, animation, speaker & room atmosphere effects.",
    items: [
      { name: "Voice Frame", icon: "🎙️", price: "85,000", rarity: "Epic", desc: "Animated voice activity frame" },
      { name: "Voice Animation", icon: "🎵", price: "95,000", rarity: "Epic", desc: "Visual voice waveform animation" },
      { name: "Speaker Effect", icon: "🔊", price: "110,000", rarity: "Legendary", desc: "Premium speaker visual effect" },
      { name: "Room Atmosphere", icon: "🌌", price: "140,000", rarity: "Legendary", desc: "Ambient room atmosphere theme" },
    ],
    features: ["Real-Time Audio Sync", "Visual Feedback"],
    actions: ["Activate", "Customize"],
  },
  {
    id: "event_items",
    name: "Event Items",
    icon: "🎮",
    gradient: "from-teal-400 to-cyan-500",
    color: "#14B8A6",
    subtitle: "Event Treasure Box",
    description: "Event frames, badges, limited gifts & competition items.",
    items: [
      { name: "Event Frames", icon: "🖼️", price: "70,000", rarity: "Epic", desc: "Special event themed frames" },
      { name: "Event Badges", icon: "🎖️", price: "55,000", rarity: "Rare", desc: "Event participation badges" },
      { name: "Limited Gifts", icon: "🎁", price: "120,000", rarity: "Legendary", desc: "Event exclusive gift items" },
      { name: "Competition Items", icon: "🏆", price: "200,000", rarity: "Mythic", desc: "Tournament competition rewards" },
    ],
    features: ["Time Limited", "Event Exclusive", "Collectible"],
    actions: ["Collect", "Use", "Exchange"],
  },
  {
    id: "vip_mall",
    name: "VIP Mall",
    icon: "👑",
    gradient: "from-amber-300 to-yellow-500",
    color: "#FCD34D",
    subtitle: "Royal VIP Store",
    description: "Exclusive items for VIP users only.",
    items: [
      { name: "Ultra Frames", icon: "💎", price: "500,000", rarity: "Mythic", desc: "Ultra premium VIP only frames" },
      { name: "Royal Entry Effects", icon: "👑", price: "800,000", rarity: "Mythic", desc: "Royal entrance effects for VIP" },
      { name: "Legendary Gifts", icon: "⭐", price: "1,500,000", rarity: "Mythic", desc: "VIP exclusive legendary gifts" },
      { name: "Exclusive Themes", icon: "🎨", price: "600,000", rarity: "Mythic", desc: "VIP only profile themes" },
    ],
    features: ["VIP Only Access", "Ultra Premium Items", "Exclusive Collections"],
    actions: ["Purchase", "Activate"],
  },
  {
    id: "limited_edition",
    name: "Limited Edition",
    icon: "🔥",
    gradient: "from-orange-500 to-red-600",
    color: "#EA580C",
    subtitle: "Rare Collection",
    description: "Time-limited, festival, anniversary & global event items.",
    items: [
      { name: "Time Limited Items", icon: "⏰", price: "300,000", rarity: "Mythic", desc: "Available for limited time only" },
      { name: "Festival Items", icon: "🎄", price: "150,000", rarity: "Legendary", desc: "Seasonal festival exclusives" },
      { name: "Anniversary Items", icon: "🎂", price: "400,000", rarity: "Mythic", desc: "Platform anniversary collectibles" },
      { name: "Global Event Items", icon: "🌍", price: "500,000", rarity: "Mythic", desc: "Global event commemorative items" },
    ],
    features: ["Limited Time", "Rare Collectibles", "Never Restocked"],
    actions: ["Buy Before Expiry", "Collect"],
  },
  {
    id: "inventory",
    name: "Inventory",
    icon: "🎒",
    gradient: "from-slate-400 to-gray-500",
    color: "#64748B",
    subtitle: "Personal Collection",
    description: "View owned, active, expired & gift received items.",
    items: [
      { name: "Owned Items", icon: "📦", price: "—", rarity: "—", desc: "All items you currently own" },
      { name: "Active Items", icon: "✅", price: "—", rarity: "—", desc: "Currently equipped items" },
      { name: "Expired Items", icon: "⏳", price: "—", rarity: "—", desc: "Items that have expired" },
      { name: "Gift Received", icon: "💌", price: "—", rarity: "—", desc: "Items received as gifts" },
    ],
    features: ["Full Collection View", "Status Tracking"],
    actions: ["Equip", "Remove", "Gift", "Sell/Exchange"],
  },
  {
    id: "payment",
    name: "Payment Center",
    icon: "💳",
    gradient: "from-green-400 to-emerald-500",
    color: "#22C55E",
    subtitle: "Premium Wallet",
    description: "Purchase items with coins, credit card, or PayPal.",
    items: [
      { name: "Buy Coins", icon: "🪙", price: "—", rarity: "—", desc: "Recharge your coin balance" },
      { name: "Purchase Item", icon: "🛒", price: "—", rarity: "—", desc: "Complete your item purchase" },
      { name: "Transaction History", icon: "📊", price: "—", rarity: "—", desc: "View all mall transactions" },
    ],
    features: ["Coins", "Credit Card", "Card Payment", "PayPal"],
    actions: ["Buy Coins", "Purchase Item", "Transaction History"],
  },
];

export const rarityStyles = {
  Common: { color: "#94A3B8", bg: "rgba(148,163,184,0.15)", border: "rgba(148,163,184,0.3)" },
  Rare: { color: "#3B82F6", bg: "rgba(59,130,246,0.15)", border: "rgba(59,130,246,0.3)" },
  Epic: { color: "#A855F7", bg: "rgba(168,85,247,0.15)", border: "rgba(168,85,247,0.3)" },
  Legendary: { color: "#F59E0B", bg: "rgba(245,158,11,0.15)", border: "rgba(245,158,11,0.3)" },
  Mythic: { color: "#EF4444", bg: "rgba(239,68,68,0.15)", border: "rgba(239,68,68,0.3)" },
  "—": { color: "#64748B", bg: "rgba(100,116,139,0.15)", border: "rgba(100,116,139,0.3)" },
};