export const dashboards = [
  {
    id: "owner",
    title: "Owner Dashboard",
    description: "Master control center — global control, analytics, finance, security, approvals, and monitoring across the entire VYRO ecosystem",
    icon: "Crown",
    path: "/owner-dashboard",
    gradient: "linear-gradient(135deg, #2F80ED, #56CCF2)",
    color: "#2F80ED",
    badge: "HIGHEST AUTHORITY",
    requiredRole: "owner",
    modules: ["Dashboard Home", "Global Search", "Country Control", "Role Management", "Applications", "Revenue Center", "Gift Center", "Coin Economy", "Rankings", "Live Monitoring", "AI Monitoring", "Security Command", "Finance Center", "Audit Center", "Broadcast", "Automation", "Business Intelligence", "Settings", "Owner Powers"],
  },
  {
    id: "sam",
    title: "SAM Dashboard",
    description: "Super Admin Manager controls users, coins, sellers, recharges, withdrawals, wallets, revenue, security, and system health",
    icon: "Shield",
    path: "/sam-dashboard",
    gradient: "linear-gradient(135deg, #D4AF37, #B8941E)",
    color: "#D4AF37",
    badge: "SUPER ADMIN",
    requiredRole: "owner",
    modules: ["Dashboard Overview", "User Management", "Coin Management", "Coin Seller Management", "Offline Recharge", "Wallet Control Center", "Withdrawal Management", "Agency & Agent Management", "Host & Streaming", "Gift & Revenue", "Reports & Analytics", "Security Center", "Admin Control", "System Health", "SAM Profile"],
  },
  {
    id: "vip",
    title: "VIP Manager Dashboard",
    description: "Enterprise VIP membership management, premium user services, VIP rewards distribution, loyalty operations, VIP engagement monitoring, exclusive events, VIP revenue analysis, and premium customer experience control center",
    icon: "Crown",
    path: "/vip-manager-dashboard",
    gradient: "linear-gradient(135deg, #D4AF37, #F59E0B)",
    color: "#D4AF37",
    badge: "VIP MANAGER",
    requiredRole: "admin",
    modules: ["Dashboard Home", "VIP Overview", "Member Management", "Level Management", "Rewards Center", "Event Management", "Host Engagement", "Revenue Center", "Retention Center", "Growth Center", "Communication", "Exclusive Benefits", "Partnerships", "Country Performance", "Top Rankings", "AI Intelligence", "Analytics", "Reports", "Team Management", "Settings", "Exclusive Tools"],
  },
  {
    id: "support",
    title: "Support Manager Dashboard",
    description: "Central customer support, complaint resolution, ticket management, dispute handling, user assistance, account recovery, fraud reporting, and service quality monitoring control center",
    icon: "LifeBuoy",
    path: "/support-manager-dashboard",
    gradient: "linear-gradient(135deg, #2F80ED, #56CCF2)",
    color: "#2F80ED",
    badge: "SUPPORT MANAGER",
    requiredRole: "admin",
    modules: ["Dashboard Home", "Support Overview", "Ticket Management", "User Support", "Host Support", "Agent Support", "Agency Support", "VIP Support", "Account Recovery", "Appeals Management", "Fraud Reports", "Payment Support", "Withdrawal Support", "Live Stream Support", "Technical Support", "Knowledge Base", "Communication", "Reports", "Staff Management", "Analytics", "Exclusive Tools"],
  },
  {
    id: "superadmin",
    title: "Super Admin Dashboard",
    description: "Central operational management and monitoring system for overseeing agencies, talent agents, hosts, and admins. Approves applications, monitors performance, tracks revenue, and maintains platform standards",
    icon: "Shield",
    path: "/super-admin-dashboard",
    gradient: "linear-gradient(135deg, #475569, #64748B)",
    color: "#475569",
    badge: "SUPER ADMIN",
    requiredRole: "admin",
    modules: ["Dashboard Home", "Agency Management", "Agent Management", "Host Management", "Admin Management", "Application Management", "Performance Monitoring", "Revenue Monitoring", "Event Monitoring", "PK Monitoring", "Reports & Violations", "Security Monitoring", "Communication Center", "Analytics Center", "Audit Log Center", "Operation Settings"],
  },
  {
    id: "reward",
    title: "Reward Manager Dashboard",
    description: "Central reward management, achievement tracking, incentive distribution, bonus campaigns, loyalty rewards, milestone rewards, event rewards, performance rewards, engagement rewards, and recognition program control center",
    icon: "Gift",
    path: "/reward-manager-dashboard",
    gradient: "linear-gradient(135deg, #F59E0B, #D97706)",
    color: "#F59E0B",
    badge: "REWARD MANAGER",
    requiredRole: "admin",
    modules: ["Dashboard Home", "Reward Overview", "Reward Management", "Achievement Rewards", "Event Rewards", "VIP Rewards", "Agent Rewards", "Agency Rewards", "Host Rewards", "User Rewards", "Loyalty Program", "Bonus Management", "Coin Rewards", "Country Performance", "Top Earners", "AI Intelligence", "Analytics", "Reports", "Team Management", "Settings", "Exclusive Tools"],
  },
  {
    id: "pkmanager",
    title: "PK Manager Dashboard",
    description: "Central PK Battle management, competition administration, ranking control, reward distribution, event organization, fair-play monitoring, performance analytics, and PK ecosystem operations control center",
    icon: "Swords",
    path: "/pk-manager-dashboard",
    gradient: "linear-gradient(135deg, #EF4444, #B91C1C)",
    color: "#EF4444",
    badge: "PK MANAGER",
    requiredRole: "admin",
    modules: ["Dashboard Home", "PK Overview", "Battle Management", "Tournament Center", "Event Management", "PK Rewards", "PK Rankings", "Global Monitoring", "AI Fair Play", "Disputes", "PK Revenue", "PK Achievements", "Host Performance", "Agency Performance", "Country Performance", "Analytics", "Communication", "Reports", "Team Management", "Settings", "Exclusive Tools"],
  },
  {
    id: "marketing",
    title: "Marketing Manager Dashboard",
    description: "Central marketing, branding, advertising, campaign management, user acquisition, host promotion, event promotion, social media management, influencer collaboration, growth analytics, and brand development control center",
    icon: "Megaphone",
    path: "/marketing-manager-dashboard",
    gradient: "linear-gradient(135deg, #3B82F6, #1D4ED8)",
    color: "#3B82F6",
    badge: "MARKETING MGR",
    requiredRole: "admin",
    modules: ["Dashboard Home", "Marketing Overview", "Campaign Management", "User Acquisition", "Host Promotion", "Agency Promotion", "Brand Management", "Social Media", "Influencer Management", "Event Promotion", "Advertising Center", "Growth Analytics", "AI Marketing Intelligence", "Brand Performance", "Communication Center", "Content Management", "Promotion Management", "Report Management", "Team Management", "Settings", "Exclusive Tools"],
  },
  {
    id: "finance",
    title: "Finance Manager Dashboard",
    description: "Central financial management, revenue monitoring, commission control, withdrawal management, payment verification, wallet auditing, financial reporting, and business profitability control center of the platform",
    icon: "DollarSign",
    path: "/finance-manager-dashboard",
    gradient: "linear-gradient(135deg, #F59E0B, #D97706)",
    color: "#F59E0B",
    badge: "FINANCE MGR",
    requiredRole: "admin",
    modules: ["Dashboard Home", "Finance Overview", "Revenue Management", "Withdrawal Management", "Payment Management", "Wallet Management", "Coin Economy", "Gift Revenue", "Commissions", "Profit & Loss", "Financial Reports", "Transaction Audit", "Fraud Detection", "Revenue Analytics", "Country Revenue", "Top Earners", "AI Intelligence", "Communication", "Team Management", "Settings", "Exclusive Tools"],
  },
  {
    id: "event",
    title: "Event Manager Dashboard",
    description: "Central event planning, event operations, competition management, seasonal campaign management, reward event administration, participation monitoring, event analytics, engagement tracking, and global event ecosystem control center",
    icon: "PartyPopper",
    path: "/event-manager-dashboard",
    gradient: "linear-gradient(135deg, #EC4899, #BE185D)",
    color: "#EC4899",
    badge: "EVENT MGR",
    requiredRole: "admin",
    modules: ["Dashboard Home", "Event Overview", "Event Management", "Competition Management", "Event Rewards", "Participation Management", "Global Monitoring", "Host Events", "Agency Events", "VIP Events", "Event Revenue", "Event Rankings", "Communication", "Festival & Seasonal", "Country Performance", "AI Intelligence", "Event Analytics", "Report Management", "Team Management", "Settings", "Exclusive Tools"],
  },
  {
    id: "country",
    title: "Country Manager Dashboard",
    description: "Highest operational control center for managing all platform activities within a specific country — users, hosts, agents, agencies, revenue, events, applications, security, and country-wide performance",
    icon: "Globe",
    path: "/country-manager-dashboard",
    gradient: "linear-gradient(135deg, #10B981, #047857)",
    color: "#10B981",
    badge: "COUNTRY MGR",
    requiredRole: "admin",
    modules: ["Country Overview", "Country Search", "User Management", "Host Management", "Agent Management", "Agency Management", "Application Center", "Country Revenue", "Country Gifts", "Country Coins", "Country Rankings", "Live Monitoring", "PK Monitoring", "Event Management", "VIP Management", "Report Management", "Security Center", "Broadcast Center", "Country Analytics", "Country Settings"],
  },
  {
    id: "business",
    title: "Business Manager Dashboard",
    description: "Central hub for daily business operations, agency performance, host productivity, revenue optimization, team coordination, growth execution, business planning, and operational efficiency — bridges Business Developers, Agencies, Talent Agents, and Management",
    icon: "Briefcase",
    path: "/business-manager-dashboard",
    gradient: "linear-gradient(135deg, #F59E0B, #D97706)",
    color: "#F59E0B",
    badge: "BUSINESS MGR",
    requiredRole: "admin",
    modules: ["Business Overview", "Team Management", "Host Performance", "Agent Management", "Agency Management", "Business Growth", "Target Management", "Revenue Management", "Campaign Management", "Event Management", "Application Management", "Communication Center", "Analytics Center", "Business Intelligence", "Performance Management", "Report Management", "Document Management", "Operations Center", "Notification Center", "Exclusive Tools"],
  },
  {
    id: "bdev",
    title: "Business Developer Dashboard",
    description: "Primary growth, recruitment, expansion, and partnership management center — recruits hosts, onboards talent agents, develops agencies, builds strategic partnerships, expands into new markets, increases revenue, and achieves business targets",
    icon: "Compass",
    path: "/business-developer-dashboard",
    gradient: "linear-gradient(135deg, #3B82F6, #1D4ED8)",
    color: "#3B82F6",
    badge: "BIZ DEVELOPER",
    requiredRole: "admin",
    modules: ["Business Overview", "Host Recruitment", "Talent Agent Recruitment", "Agency Development", "Lead Management", "Market Expansion", "Partnership Management", "Campaign Management", "Revenue Growth", "Regional Performance", "Application Management", "Communication Center", "Event Development", "Performance Tracking", "Business Intelligence", "Task Management", "Document Center", "Analytics Center", "Business Settings", "Exclusive Tools"],
  },
  {
    id: "seller",
    title: "Offline Coins Seller Dashboard",
    description: "Complete offline coins seller system — premium seller management, manual recharge, customer management, seller levels, packages, rewards, rankings, security, wallet, OCS policy, report submission, and admin controls with dark luxury glassmorphism UI",
    icon: "Store",
    path: "/seller-dashboard",
    gradient: "linear-gradient(135deg, #FFD700, #22D3EE)",
    color: "#FFD700",
    badge: "SELLER SYSTEM",
    requiredRole: "user",
    modules: ["Seller Panel", "Manual Recharge", "Recharge History", "Recharge Analytics", "Customer Management", "Seller Earnings", "Monthly Reports", "Daily Reports", "Seller Wallet", "Withdraw Requests", "Bonus Control", "Starter Packages", "Medium Packages", "VIP Packages", "Bronze Seller", "Silver Seller", "Gold Seller", "Diamond Seller", "Seller Rewards", "Top Rankings", "Country Rankings", "Security Center", "Admin Controls", "Recharge Process", "Notifications", "OCS Policy", "Report Submission", "Authority & Terms", "Send Report", "Report Types", "Approval History"],
  },
  {
    id: "admin",
    title: "Admin Dashboard",
    description: "Operational support and management center for handling assigned Agencies, Talent Agents, and Hosts — verification, support, monitoring, reporting, communication, compliance management, and operational coordination under Super Admin authority",
    icon: "UserCog",
    path: "/admin-dashboard",
    gradient: "linear-gradient(135deg, #64748B, #475569)",
    color: "#64748B",
    badge: "ADMIN",
    requiredRole: "admin",
    modules: ["Agency Management", "Talent Agent Management", "Host Management", "Application Management", "Verification Center", "Support Center", "Reports & Compliance", "Event Support", "PK Support", "Communication Center", "Reporting & Analytics", "Audit Log Center", "Admin Tools"],
  },
];