// Detailed data for each VIP level's dedicated detail screen.
// Merges with vipLevels + vipPricingTiers from vipData.js at render time.

export const vipLevelDetails = [
  {
    levelId: 1,
    description: "VIP 1 is the entry point into the VYRO Live Connect premium ecosystem. Members receive a distinguished Bronze Crystal Shield badge that sets them apart from standard users. This tier provides foundational VIP privileges including a colored username, basic profile frame, and access to exclusive VIP emojis. Perfect for users beginning their premium journey.",
    unlockRequirements: ["Accumulate 100,000 coins in total gifts sent", "Reach Level 10 user profile", "Complete account verification (phone + face)", "Maintain active account for 7 days"],
    exclusiveAssets: {
      avatarFrame: "Bronze Crystal Shield Frame",
      badge: "VIP 1 Bronze Badge",
      medal: "Crystal Bronze Medal",
      chatBubble: "VIP Bronze Chat Bubble",
      entryEffect: "Crystal Shield Entry Effect",
      namePlate: "Bronze Name Plate",
    },
    bgGradient: "from-amber-900 via-amber-950 to-[#0A0118]",
    accentGradient: "from-amber-500 to-yellow-700",
  },
  {
    levelId: 2,
    description: "VVIP elevates the premium experience with a stunning Silver Crystal Crown. Members unlock premium profile frames, exclusive chat bubbles, and a refined silver aesthetic. This tier introduces gift cashback rewards and enhanced priority support, making it ideal for active community members seeking greater recognition.",
    unlockRequirements: ["Accumulate 200,000 coins in total gifts sent", "Reach Level 20 user profile", "Complete phone + face verification", "Maintain VYO activity for 14 days"],
    exclusiveAssets: {
      avatarFrame: "Silver Crystal Crown Frame",
      badge: "VVIP Silver Badge",
      medal: "Crystal Silver Medal",
      chatBubble: "VVIP Silver Chat Bubble",
      entryEffect: "Crystal Crown Entry Effect",
      namePlate: "Silver Name Plate",
    },
    bgGradient: "from-slate-700 via-slate-900 to-[#0A0118]",
    accentGradient: "from-slate-300 to-slate-500",
  },
  {
    levelId: 3,
    description: "SVIP brings the prestige of a Golden Sapphire Crown. Members enjoy animated profile frames, premium chat bubbles, and a striking entrance effect that announces their arrival. With exclusive stickers and a 3% gift cashback, SVIP members stand out as valued contributors in any room they enter.",
    unlockRequirements: ["Accumulate 500,000 coins in total gifts sent", "Reach Level 30 user profile", "Complete full identity verification", "Maintain active gifting history for 30 days"],
    exclusiveAssets: {
      avatarFrame: "Golden Sapphire Animated Frame",
      badge: "SVIP Gold Badge",
      medal: "Sapphire Gold Medal",
      chatBubble: "SVIP Premium Chat Bubble",
      entryEffect: "Golden Entrance Animation",
      namePlate: "Gold Sapphire Name Plate",
    },
    bgGradient: "from-yellow-700 via-amber-950 to-[#0A0118]",
    accentGradient: "from-yellow-400 to-amber-500",
  },
  {
    levelId: 4,
    description: "SSVIP dazzles with a Diamond Crystal Shield, combining animated frames and entrance effects with an exclusive username color. Members gain room entry priority, ensuring they always get a seat in popular rooms. The cyan-blue aesthetic and 5% gift cashback make this tier a favorite among dedicated gifting enthusiasts.",
    unlockRequirements: ["Accumulate 800,000 coins in total gifts sent", "Reach Level 40 user profile", "Complete full identity + device verification", "Maintain active gifting for 45 days"],
    exclusiveAssets: {
      avatarFrame: "Diamond Crystal Animated Frame",
      badge: "SSVIP Diamond Badge",
      medal: "Diamond Crystal Medal",
      chatBubble: "SSVIP Exclusive Chat Bubble",
      entryEffect: "Animated Diamond Entrance Effect",
      namePlate: "Diamond Color Name Plate",
    },
    bgGradient: "from-cyan-800 via-blue-950 to-[#0A0118]",
    accentGradient: "from-cyan-400 to-blue-500",
  },
  {
    levelId: 5,
    description: "MSVIP crowns members with a Master Royal Crown, delivering luxury profile frames and a stunning vehicle entry effect. Members unlock access to exclusive gifts and premium chat bubbles. The purple-violet theme radiates sophistication, complemented by a 7% gift cashback and VIP-level support.",
    unlockRequirements: ["Accumulate 1,500,000 coins in total gifts sent", "Reach Level 50 user profile", "Complete enhanced identity verification", "Maintain active gifting for 60 days"],
    exclusiveAssets: {
      avatarFrame: "Luxury Master Royal Frame",
      badge: "MSVIP Crown Badge",
      medal: "Master Royal Medal",
      chatBubble: "MSVIP Premium Chat Bubble",
      entryEffect: "Vehicle Entry Effect",
      namePlate: "Master Royal Name Plate",
    },
    bgGradient: "from-purple-800 via-violet-950 to-[#0A0118]",
    accentGradient: "from-purple-500 to-violet-600",
  },
  {
    levelId: 6,
    description: "MSSVIP members reign with a Royal Phoenix Crown, featuring luxury animated frames and a premium entrance animation. This tier unlocks the exclusive VIP Lounge Access and a curated gift collection. The pink-rose aesthetic and 10% gift cashback make this a truly premium experience for elite members.",
    unlockRequirements: ["Accumulate 2,500,000 coins in total gifts sent", "Reach Level 60 user profile", "Complete enhanced identity + social verification", "Maintain active gifting for 75 days"],
    exclusiveAssets: {
      avatarFrame: "Luxury Animated Phoenix Frame",
      badge: "MSSVIP Crown Badge",
      medal: "Royal Phoenix Medal",
      chatBubble: "MSSVIP Premium Chat Bubble",
      entryEffect: "Premium Phoenix Entrance Animation",
      namePlate: "Royal Phoenix Name Plate",
    },
    bgGradient: "from-pink-800 via-rose-950 to-[#0A0118]",
    accentGradient: "from-pink-500 to-rose-600",
  },
  {
    levelId: 7,
    description: "MISVIP bestows an Imperial Royal Crown with a diamond profile frame and premium vehicle effect. Members receive an exclusive ID tag, VIP room access, and priority verification. This tier introduces VIP exclusive tasks, lucky draw tickets, and shop discounts, delivering a 12% gift cashback alongside full moderation capabilities.",
    unlockRequirements: ["Accumulate 5,000,000 coins in total gifts sent", "Reach Level 70 user profile", "Complete full identity + social + device verification", "Maintain active gifting for 90 days"],
    exclusiveAssets: {
      avatarFrame: "Diamond Imperial Royal Frame",
      badge: "MISVIP Royal Crown Badge",
      medal: "Imperial Royal Medal",
      chatBubble: "MISVIP Exclusive Chat Bubble",
      entryEffect: "Premium Vehicle Entry Effect",
      namePlate: "Exclusive ID Tag Name Plate",
    },
    bgGradient: "from-blue-800 via-indigo-950 to-[#0A0118]",
    accentGradient: "from-blue-400 to-indigo-600",
  },
  {
    levelId: 8,
    description: "MISSVIP represents the Ultimate Diamond Crown, featuring diamond animated frames and a legendary entrance effect. Members unlock exclusive room themes, avatar items, and VIP event access. With monthly exclusive gift packs, double daily check-in rewards, and a 15% gift cashback, this tier delivers an extraordinary premium lifestyle.",
    unlockRequirements: ["Accumulate 10,000,000 coins in total gifts sent", "Reach Level 80 user profile", "Complete all verification tiers", "Maintain active gifting for 120 days"],
    exclusiveAssets: {
      avatarFrame: "Diamond Animated Ultimate Frame",
      badge: "MISSVIP Diamond Crown Badge",
      medal: "Ultimate Diamond Medal",
      chatBubble: "MISSVIP Legendary Chat Bubble",
      entryEffect: "Legendary Diamond Entrance Effect",
      namePlate: "Ultimate Diamond Name Plate",
    },
    bgGradient: "from-purple-800 via-fuchsia-950 to-[#0A0118]",
    accentGradient: "from-purple-500 to-fuchsia-600",
  },
  {
    levelId: 9,
    description: "ULTRA MISSVIP ignites with an Ultra Dragon Crown, the pinnacle of animated frames and super entrance effects. Members gain ultra vehicle effects, exclusive gifts, and VIP event priority. With a monthly 500,000 bonus coin reward, priority seat reservations, and an exclusive seasonal avatar set, this tier offers an 18% gift cashback for the most dedicated members.",
    unlockRequirements: ["Accumulate 20,000,000 coins in total gifts sent", "Reach Level 90 user profile", "Complete all verification tiers + security clearance", "Maintain active gifting for 150 days"],
    exclusiveAssets: {
      avatarFrame: "Ultra Animated Dragon Frame",
      badge: "Ultra Crown Badge",
      medal: "Ultra Dragon Medal",
      chatBubble: "Ultra Super Chat Bubble",
      entryEffect: "Super Ultra Entrance Effect",
      namePlate: "Ultra Dragon Name Plate",
    },
    bgGradient: "from-red-800 via-orange-950 to-[#0A0118]",
    accentGradient: "from-red-500 to-orange-600",
  },
  {
    levelId: 10,
    description: "LEGEND IMISVIP embodies the Galaxy Legendary Crown, a mythical tier reserved for true legends. Members receive a legendary profile frame, mythical entrance effect, and custom chat bubble. With an exclusive username style, monthly 1,500,000 bonus coins, custom profile backgrounds, and priority feature testing, this tier delivers a 20% gift cashback and dedicated VIP support.",
    unlockRequirements: ["Accumulate 50,000,000 coins in total gifts sent", "Reach Level 100 user profile", "Complete all verification + security + social verification", "Maintain active gifting for 180 days"],
    exclusiveAssets: {
      avatarFrame: "Legendary Galaxy Profile Frame",
      badge: "Legend Crown Badge",
      medal: "Galaxy Legendary Medal",
      chatBubble: "Custom Galaxy Chat Bubble",
      entryEffect: "Mythical Galaxy Entrance Effect",
      namePlate: "Legendary Username Style Name Plate",
    },
    bgGradient: "from-indigo-800 via-purple-950 to-[#0A0118]",
    accentGradient: "from-indigo-500 to-purple-600",
  },
  {
    levelId: 11,
    description: "ROYAL IMISSVIP sits atop the VYRO Live Connect hierarchy with the Royal Emperor Throne. Members receive the ultimate animated frame, royal entrance and vehicle effects, and a custom username color and profile theme. With a dedicated account manager, premium 24/7 support, private VIP events, monthly 5,000,000 bonus coins, custom animated backgrounds, and early access to new features, this tier delivers a majestic 25% gift cashback and absolute room authority.",
    unlockRequirements: ["Accumulate 100,000,000 coins in total gifts sent", "Reach Level 120 user profile", "Complete all verification + security + social + elite clearance", "Maintain active gifting for 365 days"],
    exclusiveAssets: {
      avatarFrame: "Ultimate Royal Emperor Frame",
      badge: "Royal King Crown Badge",
      medal: "Royal Emperor Medal",
      chatBubble: "Royal Emperor Chat Bubble",
      entryEffect: "Royal Emperor Entrance Effect",
      namePlate: "Custom Royal Name Plate",
    },
    bgGradient: "from-amber-700 via-yellow-900 to-[#0A0118]",
    accentGradient: "from-amber-400 via-yellow-500 to-orange-500",
  },
];

export function getVipLevelDetail(levelId) {
  return vipLevelDetails.find((d) => d.levelId === Number(levelId));
}