// Social page data — VYRO Live Connect

export const SOCIAL_MODULES = [
  {
    id: "invite",
    title: "My Invite",
    subtitle: "Invite Friends & Earn Rewards",
    description: "My Invite is the official referral system that allows users to invite new members to join the platform using a personal invitation code or referral link. Users receive rewards when invited members register, verify their account, and complete eligible activities.",
    icon: "Ticket",
    color: "#EC4899",
    gradient: "linear-gradient(135deg, #EC4899, #BE185D)",
    stats: [
      { label: "Total Invited", value: "247", color: "#EC4899" },
      { label: "Active", value: "184", color: "#10B981" },
      { label: "Pending", value: "28", color: "#F2994A" },
      { label: "Coins Earned", value: "12,840", color: "#F59E0B" },
    ],
    shareOptions: [
      { label: "WhatsApp", icon: "MessageCircle", color: "#25D366" },
      { label: "Telegram", icon: "Send", color: "#0088CC" },
      { label: "Facebook", icon: "Facebook", color: "#1877F2" },
      { label: "Instagram", icon: "Instagram", color: "#E4405F" },
      { label: "Messenger", icon: "MessageSquare", color: "#0084FF" },
      { label: "SMS", icon: "MessageCircle", color: "#27AE60" },
      { label: "Email", icon: "Mail", color: "#F2994A" },
      { label: "More", icon: "Share2", color: "#6B7280" },
    ],
    features: [
      "Personal Invite Code", "Referral Link", "QR Code Invitation", "Copy Invite Link",
      "Social Media Sharing", "Invite History", "Total Invited Users", "Active Invited Users",
      "Pending Invitations", "Referral Rewards", "Coins Earned", "Bonus History",
      "Daily Invite Statistics", "Monthly Invite Statistics", "Leaderboard Ranking",
      "Invite Campaigns", "Referral Levels", "Referral Progress", "Referral Achievements",
    ],
    history: [
      { name: "Stella Streams", status: "Registered", reward: "50 coins", date: "2026-07-02", color: "#27AE60" },
      { name: "Ocean Voice", status: "Verified", reward: "100 coins", date: "2026-07-01", color: "#27AE60" },
      { name: "Desert Melody", status: "Pending", reward: "—", date: "2026-06-30", color: "#F2994A" },
      { name: "Mountain Echo", status: "Registered", reward: "50 coins", date: "2026-06-28", color: "#27AE60" },
      { name: "Northern Lights", status: "Inactive", reward: "—", date: "2026-06-25", color: "#EB5757" },
    ],
    actions: ["Copy Code", "Copy Link", "Generate QR", "Share", "View History", "Track Status", "Check Rewards", "Redeem Rewards", "View Ranking"],
  },
  {
    id: "people",
    title: "My People",
    subtitle: "All Your Connected Users",
    description: "My People is a complete relationship management system where users can organize everyone connected to their account. It displays followers, following, referrals, contacts, recent interactions, and community members.",
    icon: "Users",
    color: "#2F80ED",
    gradient: "linear-gradient(135deg, #2F80ED, #56CCF2)",
    stats: [
      { label: "Followers", value: "847", color: "#2F80ED" },
      { label: "Following", value: "284", color: "#56CCF2" },
      { label: "Referrals", value: "247", color: "#EC4899" },
      { label: "Online", value: "94", color: "#10B981" },
    ],
    categories: [
      { label: "All", count: "1,378", icon: "Users", color: "#6B7280" },
      { label: "Followers", count: "847", icon: "UserCheck", color: "#2F80ED" },
      { label: "Following", count: "284", icon: "UserPlus", color: "#56CCF2" },
      { label: "Referrals", count: "247", icon: "Ticket", color: "#EC4899" },
      { label: "VIP Members", count: "48", icon: "Crown", color: "#D4AF37" },
      { label: "Hosts", count: "84", icon: "Mic", color: "#EF4444" },
      { label: "Agencies", count: "12", icon: "Building2", color: "#8B5CF6" },
      { label: "Family", count: "28", icon: "Heart", color: "#EC4899" },
      { label: "Friends", count: "147", icon: "Handshake", color: "#27AE60" },
      { label: "Favorites", count: "24", icon: "Star", color: "#F59E0B" },
    ],
    people: [
      { name: "LunaStar", role: "Host", level: "LV.42", isOnline: true, isVip: true, avatar: "LS", color: "#EC4899" },
      { name: "DesertRose", role: "Host", level: "LV.38", isOnline: true, isVip: true, avatar: "DR", color: "#EF4444" },
      { name: "OceanVoice", role: "User", level: "LV.24", isOnline: false, isVip: false, avatar: "OV", color: "#2F80ED" },
      { name: "Marcus Reed", role: "Agent", level: "LV.18", isOnline: true, isVip: false, avatar: "MR", color: "#8B5CF6" },
      { name: "Sarah Chen", role: "Agency Owner", level: "LV.32", isOnline: true, isVip: true, avatar: "SC", color: "#D4AF37" },
      { name: "Mountain Echo", role: "Host", level: "LV.28", isOnline: false, isVip: false, avatar: "ME", color: "#10B981" },
    ],
    actions: ["View Profile", "Follow", "Unfollow", "Send Request", "Remove", "Block", "Report", "Message", "Voice Call", "Video Call", "Invite to Party", "Invite to Live", "Add to Favorites", "Share Profile"],
  },
  {
    id: "friends",
    title: "Friends",
    subtitle: "Mutual Friendship System",
    description: "Friends is the official friendship management system where users can send, receive, and manage friend requests. Friends can communicate instantly, join rooms together, play games, exchange gifts, and interact across the platform.",
    icon: "Handshake",
    color: "#27AE60",
    gradient: "linear-gradient(135deg, #27AE60, #2ECC71)",
    stats: [
      { label: "Friends", value: "147", color: "#27AE60" },
      { label: "Requests", value: "12", color: "#F2994A" },
      { label: "Online", value: "38", color: "#10B981" },
      { label: "Best Friends", value: "8", color: "#D4AF37" },
    ],
    tabs: [
      { label: "Friends", count: "147", icon: "Handshake", color: "#27AE60" },
      { label: "Requests", count: "12", icon: "Inbox", color: "#F2994A" },
      { label: "Sent", count: "8", icon: "Send", color: "#2F80ED" },
      { label: "Suggestions", count: "24", icon: "Sparkles", color: "#8B5CF6" },
    ],
    friends: [
      { name: "LunaStar", status: "Online", isBest: true, mutual: 28, avatar: "LS", color: "#EC4899" },
      { name: "DesertRose", status: "Online", isBest: true, mutual: 18, avatar: "DR", color: "#EF4444" },
      { name: "OceanVoice", status: "Offline", isBest: false, mutual: 12, avatar: "OV", color: "#2F80ED" },
      { name: "Marcus Reed", status: "Online", isBest: false, mutual: 8, avatar: "MR", color: "#8B5CF6" },
      { name: "Sarah Chen", status: "Online", isBest: true, mutual: 24, avatar: "SC", color: "#D4AF37" },
      { name: "Mountain Echo", status: "Offline", isBest: false, mutual: 6, avatar: "ME", color: "#10B981" },
    ],
    requests: [
      { name: "Stella Streams", mutual: 12, date: "2026-07-02", avatar: "SS", color: "#EC4899" },
      { name: "Apex Agency", mutual: 8, date: "2026-07-01", avatar: "AA", color: "#8B5CF6" },
      { name: "Golden Dawn", mutual: 4, date: "2026-06-30", avatar: "GD", color: "#F59E0B" },
    ],
    actions: ["Add Friend", "Accept", "Decline", "Cancel", "Remove", "Block", "Report", "Message", "Voice Call", "Video Call", "Invite to Party", "Invite to Live", "Send Gift", "Send Coins", "Share", "Pin Friend", "Mute", "Favorite"],
  },
];