export const HOST_INFO = {
  host_id: "HST-2026-1024",
  host_name: "Aria Chen",
  host_level: 12,
  verification_status: "Verified",
  agency_status: "VYRO Elite Agency",
  agency_id: "AGY-2026-0042",
  current_rank: 7,
  total_followers: 48500,
  total_fans: 12800,
  monthly_performance_score: 94.2,
  live_status: "offline",
  stream_duration_today: "3h 24m",
  live_audience_count: 0,
  peak_viewers: 2840,
  total_viewers: 18420,
};

export const HOST_STATS = [
  { label: "Total Followers", value: "48.5K", icon: "Users", color: "#8B5CF6", trend: "+1.2K this week" },
  { label: "Total Fans", value: "12.8K", icon: "Heart", color: "#EC4899", trend: "+340 this month" },
  { label: "Monthly Earnings", value: "$8.4K", icon: "DollarSign", color: "#D4AF37", trend: "+12% MoM" },
  { label: "Gift Earnings", value: "$6.1K", icon: "Gift", color: "#F59E0B", trend: "Top contributor" },
  { label: "Peak Viewers", value: "2,840", icon: "Eye", color: "#3B82F6", trend: "Last stream" },
  { label: "Total Viewers", value: "18.4K", icon: "TrendingUp", color: "#10B981", trend: "All-time" },
  { label: "Performance Score", value: "94.2", icon: "Gauge", color: "#8B5CF6", trend: "Excellent" },
  { label: "Engagement Rate", value: "78%", icon: "Activity", color: "#059669", trend: "Above avg" },
  { label: "Watch Time", value: "4.2 hrs", icon: "Clock", color: "#F59E0B", trend: "Avg per viewer" },
  { label: "Current Rank", value: "#7", icon: "Trophy", color: "#EF4444", trend: "Local ranking" },
];

export const HOST_MODULES = [
  {
    id: "host_overview",
    title: "Host Overview",
    icon: "User",
    color: "#8B5CF6",
    gradient: "linear-gradient(135deg, #7C3AED, #8B5CF6)",
    description: "Host performance summary and account status",
    features: [
      { label: "Host ID", value: "HST-2026-1024", icon: "Hash" },
      { label: "Host Level", value: "Level 12", icon: "Layers" },
      { label: "Verification Status", value: "Verified", icon: "BadgeCheck", status: "success" },
      { label: "Agency Status", value: "VYRO Elite Agency", icon: "Building2" },
      { label: "Current Rank", value: "#7 Local", icon: "Trophy", status: "success" },
      { label: "Total Followers", value: "48,500", icon: "Users" },
      { label: "Total Fans", value: "12,800", icon: "Heart" },
      { label: "Performance Score", value: "94.2 / 100", icon: "Gauge", status: "success" },
    ],
    actions: [
      { label: "View Profile", icon: "Eye", type: "primary" },
      { label: "Edit Profile", icon: "Pencil", type: "secondary" },
      { label: "View Performance", icon: "BarChart3", type: "secondary" },
    ],
  },
  {
    id: "live_streaming_center",
    title: "Live Streaming Center",
    icon: "Radio",
    color: "#EF4444",
    gradient: "linear-gradient(135deg, #DC2626, #EF4444)",
    description: "Manage live streams, scheduling, and analytics",
    features: [
      { label: "Live Status", value: "Offline", icon: "Radio", detail: "Not streaming", status: "danger" },
      { label: "Stream Duration", value: "3h 24m", icon: "Clock", detail: "Today's total" },
      { label: "Live Audience", value: "0", icon: "Users", detail: "Current viewers" },
      { label: "Peak Viewers", value: "2,840", icon: "Eye", detail: "Last stream peak", status: "success" },
      { label: "Total Viewers", value: "18,420", icon: "TrendingUp", detail: "All-time" },
      { label: "Stream History", value: "246 streams", icon: "History", detail: "Lifetime" },
    ],
    recentStreams: [
      { title: "Late Night Vibes", date: "2026-07-01", duration: "2h 15m", viewers: 2840, earnings: "$420" },
      { title: "Morning Coffee Chat", date: "2026-06-30", duration: "1h 30m", viewers: 1850, earnings: "$280" },
      { title: "Weekend Party", date: "2026-06-28", duration: "3h 45m", viewers: 3200, earnings: "$680" },
    ],
    actions: [
      { label: "Go Live", icon: "Radio", type: "danger" },
      { label: "End Live", icon: "Square", type: "secondary" },
      { label: "Schedule Live", icon: "CalendarPlus", type: "primary" },
      { label: "View Live Analytics", icon: "BarChart3", type: "secondary" },
    ],
  },
  {
    id: "earnings_center",
    title: "Earnings Center",
    icon: "DollarSign",
    color: "#D4AF37",
    gradient: "linear-gradient(135deg, #B8941E, #D4AF37)",
    description: "Track host earnings, gifts, bonuses, and withdrawals",
    features: [
      { label: "Total Earnings", value: "$42,800", icon: "DollarSign", detail: "All-time" },
      { label: "Daily Earnings", value: "$280", icon: "Sun", detail: "Today" },
      { label: "Weekly Earnings", value: "$1,920", icon: "CalendarDays", detail: "This week" },
      { label: "Monthly Earnings", value: "$8,400", icon: "Calendar", detail: "Current month" },
      { label: "Gift Earnings", value: "$6,100", icon: "Gift", detail: "From viewers" },
      { label: "Bonus Earnings", value: "$1,200", icon: "Award", detail: "Performance bonus" },
      { label: "Commission Earnings", value: "$1,100", icon: "Percent", detail: "Agency share" },
    ],
    earningsBreakdown: [
      { month: "Jan", value: 5.8 },
      { month: "Feb", value: 6.2 },
      { month: "Mar", value: 7.1 },
      { month: "Apr", value: 6.8 },
      { month: "May", value: 7.5 },
      { month: "Jun", value: 8.4 },
    ],
    transactions: [
      { type: "Gift Received", detail: "Luxury Crown from Fan", amount: "+$45", date: "2026-07-01", status: "completed" },
      { type: "Withdrawal", detail: "Bank Transfer", amount: "-$2,000", date: "2026-06-28", status: "completed" },
      { type: "Bonus", detail: "Monthly Performance Bonus", amount: "+$500", date: "2026-06-30", status: "completed" },
      { type: "Gift Received", detail: "Diamond Ring from Fan", amount: "+$120", date: "2026-07-01", status: "completed" },
    ],
    actions: [
      { label: "View Earnings Report", icon: "FileText", type: "primary" },
      { label: "Withdraw Earnings", icon: "ArrowDownToLine", type: "success" },
      { label: "Download Statement", icon: "Download", type: "secondary" },
      { label: "Transaction History", icon: "History", type: "secondary" },
    ],
  },
  {
    id: "audience_analytics",
    title: "Audience Analytics",
    icon: "BarChart3",
    color: "#059669",
    gradient: "linear-gradient(135deg, #047857, #059669)",
    description: "Viewer analytics, demographics, and engagement metrics",
    features: [
      { label: "Viewer Analytics", value: "18.4K", icon: "Eye", detail: "Total unique viewers" },
      { label: "Follower Growth", value: "+1.2K", icon: "TrendingUp", detail: "This week", status: "success" },
      { label: "Audience Demographics", value: "32 countries", icon: "Globe", detail: "Global reach" },
      { label: "Audience Retention", value: "84%", icon: "Repeat", detail: "Return rate", status: "success" },
      { label: "Engagement Rate", value: "78%", icon: "Activity", detail: "Above average", status: "success" },
      { label: "Watch Time", value: "4.2 hrs", icon: "Clock", detail: "Avg per viewer" },
    ],
    demographics: [
      { country: "United States", flag: "🇺🇸", pct: 28, color: "#3B82F6" },
      { country: "United Kingdom", flag: "🇬🇧", pct: 18, color: "#8B5CF6" },
      { country: "Japan", flag: "🇯🇵", pct: 15, color: "#EC4899" },
      { country: "Germany", flag: "🇩🇪", pct: 12, color: "#F59E0B" },
      { country: "Brazil", flag: "🇧🇷", pct: 9, color: "#10B981" },
    ],
    engagement: [
      { metric: "Chat Messages", value: 85, max: 100, color: "#3B82F6" },
      { metric: "Gift Interactions", value: 92, max: 100, color: "#D4AF37" },
      { metric: "Follow Conversions", value: 68, max: 100, color: "#10B981" },
      { metric: "Share Rate", value: 45, max: 100, color: "#EC4899" },
    ],
    actions: [
      { label: "View Reports", icon: "FileText", type: "primary" },
      { label: "Export Analytics", icon: "Download", type: "secondary" },
    ],
  },
  {
    id: "host_tasks_rewards",
    title: "Host Tasks & Rewards",
    icon: "CheckSquare",
    color: "#F59E0B",
    gradient: "linear-gradient(135deg, #D97706, #F59E0B)",
    description: "Daily tasks, missions, and reward programs",
    features: [
      { label: "Daily Tasks", value: "4 / 6", icon: "Sun", detail: "2 remaining", status: "warning" },
      { label: "Weekly Tasks", value: "8 / 10", icon: "CalendarDays", detail: "In progress" },
      { label: "Monthly Missions", value: "3 / 5", icon: "Target", detail: "60% complete" },
      { label: "Reward Programs", value: "Active", icon: "Gift", detail: "3 programs", status: "success" },
      { label: "Achievement Rewards", value: "$850", icon: "Award", detail: "Earned this month" },
    ],
    tasks: [
      { name: "Stream for 2 hours", type: "daily", completed: true, reward: "$50" },
      { name: "Reach 500 viewers", type: "daily", completed: true, reward: "$75" },
      { name: "Receive 10 gifts", type: "daily", completed: false, reward: "$60" },
      { name: "Gain 50 new followers", type: "weekly", completed: false, reward: "$150" },
      { name: "Top 10 monthly ranking", type: "monthly", completed: false, reward: "$500" },
    ],
    badges: [
      { name: "Rising Star", icon: "🌟", earned: true },
      { name: "Fan Favorite", icon: "💖", earned: true },
      { name: "Gift Magnet", icon: "🎁", earned: true },
      { name: "Stream Legend", icon: "👑", earned: false },
    ],
    actions: [
      { label: "Complete Task", icon: "CheckCircle", type: "success" },
      { label: "Claim Reward", icon: "Gift", type: "primary" },
      { label: "View Progress", icon: "TrendingUp", type: "secondary" },
    ],
  },
  {
    id: "content_management",
    title: "Content Management",
    icon: "FolderOpen",
    color: "#3B82F6",
    gradient: "linear-gradient(135deg, #2563EB, #3B82F6)",
    description: "Manage live history, highlights, and media library",
    features: [
      { label: "Live History", value: "246 streams", icon: "History", detail: "Lifetime" },
      { label: "Highlights", value: "32 clips", icon: "Star", detail: "Saved moments" },
      { label: "Stream Archive", value: "180 hours", icon: "Archive", detail: "Stored content" },
      { label: "Media Library", value: "1.2 GB", icon: "Image", detail: "Used of 5 GB" },
    ],
    mediaLibrary: [
      { title: "Best of June", type: "Highlight", date: "2026-06-30", size: "45 MB", icon: "Star" },
      { title: "Fan Meetup Clip", type: "Clip", date: "2026-06-28", size: "28 MB", icon: "Film" },
      { title: "PK Battle Win", type: "Highlight", date: "2026-06-25", size: "62 MB", icon: "Star" },
      { title: "Profile Banner", type: "Image", date: "2026-06-20", size: "3 MB", icon: "Image" },
    ],
    actions: [
      { label: "Upload Content", icon: "Upload", type: "primary" },
      { label: "Delete Content", icon: "Trash2", type: "danger" },
      { label: "Manage Media", icon: "FolderOpen", type: "secondary" },
    ],
  },
  {
    id: "host_ranking_center",
    title: "Host Ranking Center",
    icon: "Trophy",
    color: "#EC4899",
    gradient: "linear-gradient(135deg, #DB2777, #EC4899)",
    description: "Local, global, and event rankings with leaderboards",
    features: [
      { label: "Local Ranking", value: "#7", icon: "MapPin", detail: "In your region", status: "success" },
      { label: "Global Ranking", value: "#142", icon: "Globe", detail: "Worldwide" },
      { label: "Event Ranking", value: "#3", icon: "Calendar", detail: "Summer Cup 2026", status: "success" },
      { label: "Host Leaderboard", value: "Top 5%", icon: "Trophy", detail: "This month", status: "success" },
    ],
    leaderboard: [
      { rank: 1, name: "Luna Park", followers: "82.3K", score: 98.4, avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100", isYou: false },
      { rank: 2, name: "Sofia Diaz", followers: "71.8K", score: 96.1, avatar: "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=100", isYou: false },
      { rank: 3, name: "Mei Wong", followers: "65.2K", score: 95.3, avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100", isYou: false },
      { rank: 7, name: "Aria Chen (You)", followers: "48.5K", score: 94.2, avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100", isYou: true },
    ],
    actions: [
      { label: "View Rankings", icon: "Trophy", type: "primary" },
      { label: "View Competitors", icon: "Users", type: "secondary" },
    ],
  },
  {
    id: "support_compliance",
    title: "Support & Compliance",
    icon: "ShieldCheck",
    color: "#1D4ED8",
    gradient: "linear-gradient(135deg, #1E40AF, #1D4ED8)",
    description: "Guidelines, violations, warnings, and appeals",
    features: [
      { label: "Host Guidelines", value: "Compliant", icon: "BookOpen", detail: "Up to date", status: "success" },
      { label: "Violations", value: "0", icon: "AlertTriangle", detail: "No violations", status: "success" },
      { label: "Warnings", value: "0", icon: "AlertCircle", detail: "Clean record", status: "success" },
      { label: "Appeals", value: "0", icon: "Scale", detail: "None pending" },
    ],
    complianceHistory: [
      { type: "Review", detail: "Monthly compliance review", date: "2026-06-30", status: "passed" },
      { type: "Achievement", detail: "100% guideline compliance", date: "2026-06-15", status: "earned" },
      { type: "Training", detail: "Safety training completed", date: "2026-06-01", status: "completed" },
    ],
    actions: [
      { label: "Submit Appeal", icon: "Scale", type: "primary" },
      { label: "Contact Support", icon: "MessageSquare", type: "secondary" },
      { label: "View Compliance Report", icon: "FileText", type: "secondary" },
    ],
  },
];