export const applicationTypes = [
  {
    id: "host",
    name: "Host Application",
    icon: "🎙️",
    gradient: "from-red-400 to-orange-500",
    eligibility: "Any verified user can apply to become a Host.",
    route: "Selected Agent or Agency Dashboard",
    fields: ["Full Name", "VYRO ID", "Country", "WhatsApp Number", "Identity Documents", "Agency ID (Optional)", "Agent ID (Optional)"],
    hasAgencySelection: true,
    afterApproval: ["Host Account Activated", "Host linked to selected Agency or Agent", "Host ID Generated Automatically"],
  },
  {
    id: "agency",
    name: "Agency Application",
    icon: "🏢",
    gradient: "from-blue-400 to-indigo-500",
    eligibility: "Approved Host Status Required",
    route: "Admin Dashboard",
    fields: ["VYRO ID", "Host ID", "Experience Details", "Required Documents"],
    afterApproval: ["Agency Account Created", "Agency ID Generated Automatically"],
  },
  {
    id: "agent",
    name: "Agent Application",
    icon: "🤝",
    gradient: "from-cyan-400 to-blue-500",
    eligibility: "Approved Host Status Required",
    route: "Admin Dashboard",
    fields: ["VYRO ID", "Host ID", "Experience Details", "Documents"],
    afterApproval: ["Agent Account Created", "Agent ID Generated Automatically"],
  },
  {
    id: "admin",
    name: "Admin Application",
    icon: "🛡️",
    gradient: "from-violet-400 to-purple-500",
    eligibility: "Approved Host + Approved Agent OR Agency",
    route: "Super Admin Dashboard",
    fields: ["VYRO ID", "Host ID", "Agent/Agency ID", "Experience Details"],
    afterApproval: ["Admin Access Granted"],
  },
  {
    id: "super_admin",
    name: "Super Admin Application",
    icon: "👑",
    gradient: "from-amber-400 to-yellow-500",
    eligibility: "Approved Host + Agent + Agency + Admin",
    route: "Country Manager Dashboard",
    fields: ["VYRO ID", "Host ID", "Agent ID", "Agency ID", "Admin ID"],
    afterApproval: ["Super Admin Access Granted"],
  },
  {
    id: "business_manager",
    name: "Business Manager",
    icon: "💼",
    gradient: "from-emerald-400 to-green-500",
    eligibility: "Owner Approval Required",
    route: "Owner Dashboard",
    fields: ["VYRO ID", "Experience Details", "Documents"],
    afterApproval: ["Business Manager Access Granted"],
  },
  {
    id: "business_developer",
    name: "Business Developer",
    icon: "📈",
    gradient: "from-teal-400 to-cyan-500",
    eligibility: "Owner Approval Required",
    route: "Owner Dashboard",
    fields: ["VYRO ID", "Experience Details", "Documents"],
    afterApproval: ["Business Developer Access Granted"],
  },
  {
    id: "country_manager",
    name: "Country Manager",
    icon: "🌍",
    gradient: "from-green-400 to-emerald-500",
    eligibility: "Owner Approval Required",
    route: "Owner Dashboard",
    fields: ["VYRO ID", "Country", "Experience Details", "Documents"],
    afterApproval: ["Country Manager Access Granted"],
  },
  {
    id: "reward_manager",
    name: "Reward Manager",
    icon: "🎁",
    gradient: "from-pink-400 to-rose-500",
    eligibility: "Owner Approval Required",
    route: "Owner Dashboard",
    fields: ["VYRO ID", "Experience Details", "Documents"],
    afterApproval: ["Reward Manager Access Granted"],
  },
  {
    id: "vip_manager",
    name: "VIP Manager",
    icon: "💎",
    gradient: "from-purple-400 to-violet-500",
    eligibility: "Owner Approval Required",
    route: "Owner Dashboard",
    fields: ["VYRO ID", "Experience Details", "Documents"],
    afterApproval: ["VIP Manager Access Granted"],
  },
  {
    id: "finance_manager",
    name: "Finance Manager",
    icon: "💰",
    gradient: "from-yellow-400 to-amber-500",
    eligibility: "Owner Approval Required",
    route: "Owner Dashboard",
    fields: ["VYRO ID", "Experience Details", "Documents"],
    afterApproval: ["Finance Manager Access Granted"],
  },
  {
    id: "support_manager",
    name: "Support Manager",
    icon: "🛟",
    gradient: "from-sky-400 to-blue-500",
    eligibility: "Owner Approval Required",
    route: "Owner Dashboard",
    fields: ["VYRO ID", "Experience Details", "Documents"],
    afterApproval: ["Support Manager Access Granted"],
  },
];

export const statusTypes = [
  { key: "pending", label: "Pending Review", icon: "⏳", color: "text-amber-500", bg: "bg-amber-50", border: "border-amber-200" },
  { key: "verification", label: "Under Verification", icon: "🔍", color: "text-blue-500", bg: "bg-blue-50", border: "border-blue-200" },
  { key: "approved", label: "Approved", icon: "✅", color: "text-green-500", bg: "bg-green-50", border: "border-green-200" },
  { key: "rejected", label: "Rejected", icon: "❌", color: "text-red-500", bg: "bg-red-50", border: "border-red-200" },
  { key: "delayed", label: "Delayed / On Hold", icon: "⏸️", color: "text-purple-500", bg: "bg-purple-50", border: "border-purple-200" },
  { key: "resubmission", label: "Resubmission Required", icon: "🔄", color: "text-orange-500", bg: "bg-orange-50", border: "border-orange-200" },
];

export const myApplications = [
  { id: "APP-2026-001", type: "host", typeName: "Host Application", date: "Jun 28, 2026", status: "verification", authority: "Agent Dashboard" },
  { id: "APP-2026-002", type: "agency", typeName: "Agency Application", date: "Jun 15, 2026", status: "approved", authority: "Admin Dashboard" },
  { id: "APP-2025-089", type: "agent", typeName: "Agent Application", date: "Dec 03, 2025", status: "approved", authority: "Admin Dashboard" },
];