export const AGENT_INFO = {
  agent_id: "AGT-2026-0128",
  agent_name: "Marcus Lin",
  agent_level: 6,
  verification_status: "Verified",
  assigned_agency: "VYRO Elite Agency",
  agency_id: "AGY-2026-0042",
  total_recruits: 84,
  active_hosts: 62,
  monthly_target_pct: 78,
  performance_score: 91.5,
  conversion_rate: 72,
  compliance_score: 98,
};

export const AGENT_STATS = [
  { label: "Total Recruits", value: "84", icon: "Users", color: "#8B5CF6", trend: "+6 this month" },
  { label: "Active Hosts", value: "62", icon: "UserCheck", color: "#10B981", trend: "73.8% active" },
  { label: "Monthly Recruitment", value: "12", icon: "UserPlus", color: "#3B82F6", trend: "New hosts" },
  { label: "Target Achievement", value: "78%", icon: "Target", color: "#EC4899", trend: "On track" },
  { label: "Commission Earnings", value: "$14.2K", icon: "DollarSign", color: "#D4AF37", trend: "+8.4% MoM" },
  { label: "Performance Score", value: "91.5", icon: "Gauge", color: "#8B5CF6", trend: "Excellent" },
  { label: "Conversion Rate", value: "72%", icon: "TrendingUp", color: "#059669", trend: "+4% improvement" },
  { label: "Completed Tasks", value: "28", icon: "CheckCircle", color: "#10B981", trend: "This week" },
  { label: "Pending Tasks", value: "5", icon: "Clock", color: "#F59E0B", trend: "Due soon" },
  { label: "Compliance Score", value: "98", icon: "ShieldCheck", color: "#1D4ED8", trend: "Outstanding" },
];

export const AGENT_MODULES = [
  {
    id: "agent_overview",
    title: "Agent Overview",
    icon: "User",
    color: "#8B5CF6",
    gradient: "linear-gradient(135deg, #7C3AED, #8B5CF6)",
    description: "Agent profile, level, verification, and key metrics",
    features: [
      { label: "Agent ID", value: "AGT-2026-0128", icon: "Hash" },
      { label: "Agent Level", value: "Level 6", icon: "Layers" },
      { label: "Verification Status", value: "Verified", icon: "BadgeCheck", status: "success" },
      { label: "Assigned Agency", value: "VYRO Elite Agency", icon: "Building2" },
      { label: "Total Recruits", value: "84", icon: "Users" },
      { label: "Active Hosts", value: "62", icon: "UserCheck", status: "success" },
      { label: "Monthly Target", value: "78% Complete", icon: "Target", status: "warning" },
      { label: "Performance Score", value: "91.5 / 100", icon: "Gauge", status: "success" },
    ],
    actions: [
      { label: "View Profile", icon: "Eye", type: "primary" },
      { label: "Edit Profile", icon: "Pencil", type: "secondary" },
    ],
  },
  {
    id: "recruitment_management",
    title: "Recruitment Management",
    icon: "UserPlus",
    color: "#3B82F6",
    gradient: "linear-gradient(135deg, #2563EB, #3B82F6)",
    description: "Manage recruitment pipeline and candidate tracking",
    features: [
      { label: "Recruitment Pipeline", value: "5 stages", icon: "GitBranch", detail: "Active flow" },
      { label: "New Applications", value: "18", icon: "FileText", detail: "Pending review" },
      { label: "Candidate Tracking", value: "42", icon: "UserSearch", detail: "In pipeline" },
      { label: "Recruitment Statistics", value: "72%", icon: "BarChart3", detail: "Conversion rate" },
    ],
    pipeline: [
      { stage: "Application Received", count: 18, color: "#3B82F6" },
      { stage: "Initial Screening", count: 12, color: "#8B5CF6" },
      { stage: "Interview Scheduled", count: 8, color: "#EC4899" },
      { stage: "Interview Completed", count: 5, color: "#F59E0B" },
      { stage: "Approved & Onboarded", count: 3, color: "#10B981" },
    ],
    candidates: [
      { name: "Elena Ruiz", id: "CND-2041", stage: "Screening", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100", date: "2026-06-30" },
      { name: "Aisha Khan", id: "CND-2042", stage: "Interview", avatar: "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=100", date: "2026-07-01" },
      { name: "Jiwoo Park", id: "CND-2043", stage: "Review", avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100", date: "2026-07-02" },
      { name: "Sara Cohen", id: "CND-2044", stage: "Approved", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100", date: "2026-06-28" },
    ],
    actions: [
      { label: "Invite Host", icon: "UserPlus", type: "primary" },
      { label: "Approve Candidate", icon: "CheckCircle", type: "success" },
      { label: "Reject Candidate", icon: "XCircle", type: "danger" },
      { label: "Contact Candidate", icon: "MessageSquare", type: "secondary" },
    ],
  },
  {
    id: "host_support_center",
    title: "Host Support Center",
    icon: "Headphones",
    color: "#EC4899",
    gradient: "linear-gradient(135deg, #DB2777, #EC4899)",
    description: "Support and manage assigned hosts",
    features: [
      { label: "Assigned Hosts", value: "62", icon: "Users", detail: "Under your management" },
      { label: "Host Performance", value: "88.3 avg", icon: "Gauge", detail: "Performance score" },
      { label: "Host Activity", value: "Active", icon: "Activity", detail: "Real-time monitoring", status: "success" },
      { label: "Host Issues", value: "3 open", icon: "AlertCircle", detail: "Need attention", status: "warning" },
    ],
    hosts: [
      { name: "Aria Chen", id: "HST-1024", performance: 94, status: "active", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100" },
      { name: "Luna Park", id: "HST-1031", performance: 89, status: "active", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100" },
      { name: "Sofia Diaz", id: "HST-1038", performance: 85, status: "active", avatar: "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=100" },
      { name: "Mei Wong", id: "HST-1045", performance: 72, status: "inactive", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100" },
    ],
    actions: [
      { label: "Contact Host", icon: "MessageSquare", type: "primary" },
      { label: "View Host Profile", icon: "Eye", type: "secondary" },
      { label: "Submit Support Request", icon: "LifeBuoy", type: "secondary" },
    ],
  },
  {
    id: "target_kpi_center",
    title: "Target & KPI Center",
    icon: "Target",
    color: "#10B981",
    gradient: "linear-gradient(135deg, #059669, #10B981)",
    description: "Track daily, weekly, and monthly targets",
    features: [
      { label: "Daily Targets", value: "3 / 5", icon: "Sun", detail: "60% complete", status: "warning" },
      { label: "Weekly Targets", value: "12 / 15", icon: "CalendarDays", detail: "80% complete", status: "success" },
      { label: "Monthly Targets", value: "78%", icon: "Calendar", detail: "On track" },
      { label: "Recruitment Goals", value: "12 / 15", icon: "UserPlus", detail: "Hosts recruited" },
      { label: "Performance Score", value: "91.5", icon: "Gauge", detail: "Excellent", status: "success" },
    ],
    kpis: [
      { name: "Daily Recruitment", value: 3, target: 5, unit: "" },
      { name: "Weekly Onboarding", value: 12, target: 15, unit: "" },
      { name: "Monthly Target", value: 78, target: 100, unit: "%" },
      { name: "Host Retention", value: 88, target: 85, unit: "%" },
      { name: "Response Time", value: 92, target: 90, unit: "%" },
      { name: "Conversion Rate", value: 72, target: 70, unit: "%" },
    ],
    actions: [
      { label: "View KPI Report", icon: "FileBarChart", type: "primary" },
      { label: "Track Progress", icon: "TrendingUp", type: "secondary" },
    ],
  },
  {
    id: "earnings_commission",
    title: "Earnings & Commission",
    icon: "DollarSign",
    color: "#D4AF37",
    gradient: "linear-gradient(135deg, #B8941E, #D4AF37)",
    description: "Track agent commission, bonuses, and earnings",
    features: [
      { label: "Agent Commission", value: "$14,200", icon: "DollarSign", detail: "Total earned" },
      { label: "Recruitment Bonus", value: "$3,600", icon: "Gift", detail: "From 84 recruits" },
      { label: "Performance Bonus", value: "$2,100", icon: "Award", detail: "Based on score" },
      { label: "Monthly Earnings", value: "$4,850", icon: "Calendar", detail: "Current month" },
    ],
    earningsBreakdown: [
      { month: "Jan", value: 3.2 },
      { month: "Feb", value: 3.8 },
      { month: "Mar", value: 4.1 },
      { month: "Apr", value: 3.9 },
      { month: "May", value: 4.4 },
      { month: "Jun", value: 4.85 },
    ],
    actions: [
      { label: "View Earnings", icon: "Eye", type: "primary" },
      { label: "Download Statement", icon: "Download", type: "secondary" },
      { label: "Withdraw Earnings", icon: "ArrowDownToLine", type: "success" },
    ],
  },
  {
    id: "analytics_center",
    title: "Analytics Center",
    icon: "BarChart3",
    color: "#059669",
    gradient: "linear-gradient(135deg, #047857, #059669)",
    description: "Recruitment analytics and productivity reports",
    features: [
      { label: "Recruitment Analytics", value: "84 total", icon: "UserPlus", detail: "All-time recruits" },
      { label: "Conversion Rate", value: "72%", icon: "Percent", detail: "Applicant to host", status: "success" },
      { label: "Growth Analytics", value: "+8.4%", icon: "TrendingUp", detail: "Month over month", status: "success" },
      { label: "Productivity Reports", value: "91.5", icon: "Activity", detail: "Productivity index" },
    ],
    analytics: [
      { metric: "Applications Processed", value: 116, max: 150, color: "#3B82F6" },
      { metric: "Interviews Conducted", value: 84, max: 120, color: "#8B5CF6" },
      { metric: "Hosts Onboarded", value: 62, max: 100, color: "#10B981" },
      { metric: "Hosts Retained (90d)", value: 55, max: 62, color: "#EC4899" },
    ],
    actions: [
      { label: "Export Analytics", icon: "Download", type: "primary" },
      { label: "Generate Report", icon: "FileText", type: "secondary" },
    ],
  },
  {
    id: "tasks_achievements",
    title: "Tasks & Achievements",
    icon: "CheckSquare",
    color: "#F59E0B",
    gradient: "linear-gradient(135deg, #D97706, #F59E0B)",
    description: "Daily tasks, missions, and achievement badges",
    features: [
      { label: "Daily Tasks", value: "3 / 5", icon: "Sun", detail: "2 remaining", status: "warning" },
      { label: "Weekly Missions", value: "4 / 6", icon: "CalendarDays", detail: "In progress" },
      { label: "Monthly Challenges", value: "2 / 3", icon: "Trophy", detail: "Almost done" },
      { label: "Achievement Badges", value: "18 earned", icon: "Award", detail: "From 24 total" },
    ],
    tasks: [
      { name: "Review 3 new applications", type: "daily", completed: true, reward: "$50" },
      { name: "Contact 2 inactive hosts", type: "daily", completed: true, reward: "$30" },
      { name: "Complete 1 host interview", type: "daily", completed: false, reward: "$75" },
      { name: "Onboard 2 new hosts", type: "weekly", completed: false, reward: "$200" },
      { name: "Achieve 80% conversion rate", type: "monthly", completed: false, reward: "$500" },
    ],
    badges: [
      { name: "Top Recruiter", icon: "🏆", earned: true },
      { name: "Fast Onboarder", icon: "⚡", earned: true },
      { name: "Host Whisperer", icon: "🎯", earned: true },
      { name: "Diamond Agent", icon: "💎", earned: false },
    ],
    actions: [
      { label: "Complete Task", icon: "CheckCircle", type: "success" },
      { label: "Claim Reward", icon: "Gift", type: "primary" },
    ],
  },
  {
    id: "support_compliance",
    title: "Support & Compliance",
    icon: "ShieldCheck",
    color: "#EF4444",
    gradient: "linear-gradient(135deg, #DC2626, #EF4444)",
    description: "Compliance status, violations, and appeals",
    features: [
      { label: "Compliance Status", value: "Active", icon: "ShieldCheck", detail: "Good standing", status: "success" },
      { label: "Violations", value: "0", icon: "AlertTriangle", detail: "No violations", status: "success" },
      { label: "Warnings", value: "1", icon: "AlertCircle", detail: "Minor warning", status: "warning" },
      { label: "Appeals", value: "0", icon: "Scale", detail: "None pending" },
    ],
    complianceHistory: [
      { type: "Warning", detail: "Late response to host inquiry", date: "2026-06-20", status: "acknowledged" },
      { type: "Review", detail: "Quarterly compliance review", date: "2026-06-15", status: "passed" },
      { type: "Achievement", detail: "100% onboarding compliance", date: "2026-06-01", status: "earned" },
    ],
    actions: [
      { label: "Submit Appeal", icon: "Scale", type: "primary" },
      { label: "Contact Support", icon: "MessageSquare", type: "secondary" },
      { label: "View Compliance History", icon: "History", type: "secondary" },
    ],
  },
];